// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Create;
using Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item;
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\target-assignments\global
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GlobalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Create.CreateRequestBuilder Create
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.targetAssignments.global.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.targetAssignments.global.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.Item.GlobalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GlobalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/target-assignments/global{?Filters*,Page*,PageSize*,Sorts*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GlobalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/target-assignments/global{?Filters*,Page*,PageSize*,Sorts*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Bezalu.ImmyBot.Client.Models.GlobalTargetAssignmentResource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.GlobalTargetAssignmentResource>?> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder.GlobalRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.GlobalTargetAssignmentResource>> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder.GlobalRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Bezalu.ImmyBot.Client.Models.GlobalTargetAssignmentResource>(requestInfo, global::Bezalu.ImmyBot.Client.Models.GlobalTargetAssignmentResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder.GlobalRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder.GlobalRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class GlobalRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Filters { get; set; }
#nullable restore
#else
            public string Filters { get; set; }
#endif
            public int? Page { get; set; }
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Sorts { get; set; }
#nullable restore
#else
            public string Sorts { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GlobalRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.TargetAssignments.Global.GlobalRequestBuilder.GlobalRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
