// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Actions;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Cancel;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.LastLog;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Logs;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.OldLogs;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Phases;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Rerun;
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Resume;
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\maintenance-sessions\{sessionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSessionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cancel property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lastLog property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.LastLog.LastLogRequestBuilder LastLog
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.LastLog.LastLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Logs.LogsRequestBuilder Logs
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oldLogs property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.OldLogs.OldLogsRequestBuilder OldLogs
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.OldLogs.OldLogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phases property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Phases.PhasesRequestBuilder Phases
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Phases.PhasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rerun property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Rerun.RerunRequestBuilder Rerun
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Rerun.RerunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resume property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Resume.ResumeRequestBuilder Resume
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.Resume.ResumeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-sessions/{sessionId}{?includeActionActivities*,includeActions*,includeStages*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-sessions/{sessionId}{?includeActionActivities*,includeActions*,includeStages*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse?> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder.WithSessionItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder.WithSessionItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse>(requestInfo, global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder.WithSessionItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder.WithSessionItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithSessionItemRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("includeActionActivities")]
            public bool? IncludeActionActivities { get; set; }
            [QueryParameter("includeActions")]
            public bool? IncludeActions { get; set; }
            [QueryParameter("includeStages")]
            public bool? IncludeStages { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSessionItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceSessions.Item.WithSessionItemRequestBuilder.WithSessionItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
