// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\azure\partner-tenant-customers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PartnerTenantCustomersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.azure.partnerTenantCustomers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.Item.WithPartnerPrincipalItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.Item.WithPartnerPrincipalItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("partnerPrincipalId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.Item.WithPartnerPrincipalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.PartnerTenantCustomersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartnerTenantCustomersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/azure/partner-tenant-customers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Azure.PartnerTenantCustomers.PartnerTenantCustomersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PartnerTenantCustomersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/azure/partner-tenant-customers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
