// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Debug;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.DefaultVariables;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.DisabledPreflightScripts;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.DoesScriptHaveParamBlock;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Duplicate;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Dx;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Functions;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Global;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.LanguageService;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Local;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.References;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Run;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.RunAdhocMetascript;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.Search;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.SetPreflightScriptEnablement;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.SyntaxCheck;
using Bezalu.ImmyBot.Client.Api.V1.Scripts.ValidateParamBlockParameters;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Scripts
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\scripts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScriptsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The debug property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Debug.DebugRequestBuilder Debug
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Debug.DebugRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The defaultVariables property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DefaultVariables.DefaultVariablesRequestBuilder DefaultVariables
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DefaultVariables.DefaultVariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disabledPreflightScripts property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DisabledPreflightScripts.DisabledPreflightScriptsRequestBuilder DisabledPreflightScripts
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DisabledPreflightScripts.DisabledPreflightScriptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The doesScriptHaveParamBlock property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DoesScriptHaveParamBlock.DoesScriptHaveParamBlockRequestBuilder DoesScriptHaveParamBlock
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.DoesScriptHaveParamBlock.DoesScriptHaveParamBlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The duplicate property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Duplicate.DuplicateRequestBuilder Duplicate
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Duplicate.DuplicateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dx property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Dx.DxRequestBuilder Dx
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Dx.DxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The functions property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Functions.FunctionsRequestBuilder Functions
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Functions.FunctionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The global property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Global.GlobalRequestBuilder Global
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Global.GlobalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languageService property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.LanguageService.LanguageServiceRequestBuilder LanguageService
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.LanguageService.LanguageServiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The local property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Local.LocalRequestBuilder Local
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Local.LocalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The references property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.References.ReferencesRequestBuilder References
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.References.ReferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Run.RunRequestBuilder Run
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runAdhocMetascript property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.RunAdhocMetascript.RunAdhocMetascriptRequestBuilder RunAdhocMetascript
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.RunAdhocMetascript.RunAdhocMetascriptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Search.SearchRequestBuilder Search
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setPreflightScriptEnablement property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.SetPreflightScriptEnablement.SetPreflightScriptEnablementRequestBuilder SetPreflightScriptEnablement
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.SetPreflightScriptEnablement.SetPreflightScriptEnablementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The syntaxCheck property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.SyntaxCheck.SyntaxCheckRequestBuilder SyntaxCheck
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.SyntaxCheck.SyntaxCheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validateParamBlockParameters property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Scripts.ValidateParamBlockParameters.ValidateParamBlockParametersRequestBuilder ValidateParamBlockParameters
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Scripts.ValidateParamBlockParameters.ValidateParamBlockParametersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Scripts.ScriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScriptsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/scripts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Scripts.ScriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScriptsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/scripts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
