// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScript;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScriptWithOnboarding;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUri;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUriWithOnboarding;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.InstallOnComputer;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScript;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScriptWithOnboarding;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUri;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUriWithOnboarding;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Sync;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\provider-links\{id}\agents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bashInstallScript property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScript.BashInstallScriptRequestBuilder BashInstallScript
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScript.BashInstallScriptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bashInstallScriptWithOnboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScriptWithOnboarding.BashInstallScriptWithOnboardingRequestBuilder BashInstallScriptWithOnboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.BashInstallScriptWithOnboarding.BashInstallScriptWithOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The executableUri property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUri.ExecutableUriRequestBuilder ExecutableUri
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUri.ExecutableUriRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The executableUriWithOnboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUriWithOnboarding.ExecutableUriWithOnboardingRequestBuilder ExecutableUriWithOnboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ExecutableUriWithOnboarding.ExecutableUriWithOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installOnComputer property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.InstallOnComputer.InstallOnComputerRequestBuilder InstallOnComputer
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.InstallOnComputer.InstallOnComputerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The powershellInstallScript property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScript.PowershellInstallScriptRequestBuilder PowershellInstallScript
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScript.PowershellInstallScriptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The powershellInstallScriptWithOnboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScriptWithOnboarding.PowershellInstallScriptWithOnboardingRequestBuilder PowershellInstallScriptWithOnboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.PowershellInstallScriptWithOnboarding.PowershellInstallScriptWithOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The provisioningPackageUri property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUri.ProvisioningPackageUriRequestBuilder ProvisioningPackageUri
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUri.ProvisioningPackageUriRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The provisioningPackageUriWithOnboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUriWithOnboarding.ProvisioningPackageUriWithOnboardingRequestBuilder ProvisioningPackageUriWithOnboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.ProvisioningPackageUriWithOnboarding.ProvisioningPackageUriWithOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Sync.SyncRequestBuilder Sync
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.providerLinks.item.agents.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("agent%2Did", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.providerLinks.item.agents.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("agent%2Did", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.AgentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/provider-links/{id}/agents", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.AgentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/provider-links/{id}/agents", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
