// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Global;
using Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Local;
using Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Reload;
using Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment;
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\dynamic-provider-types
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicProviderTypesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The global property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Global.GlobalRequestBuilder Global
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Global.GlobalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The local property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Local.LocalRequestBuilder Local
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Local.LocalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reload property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Reload.ReloadRequestBuilder Reload
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.Reload.ReloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testEnvironment property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.TestEnvironmentRequestBuilder TestEnvironment
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.TestEnvironmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.DynamicProviderTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DynamicProviderTypesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dynamic-provider-types", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.DynamicProviderTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DynamicProviderTypesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dynamic-provider-types", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Bezalu.ImmyBot.Client.Models.DynamicIntegrationTypeResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.DynamicIntegrationTypeResponse>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.DynamicIntegrationTypeResponse>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Bezalu.ImmyBot.Client.Models.DynamicIntegrationTypeResponse>(requestInfo, global::Bezalu.ImmyBot.Client.Models.DynamicIntegrationTypeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.DynamicProviderTypesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.DynamicProviderTypesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.DynamicProviderTypesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DynamicProviderTypesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
