// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentOnboardingOptions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The additionalPersonIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AdditionalPersonIds { get; set; }
#nullable restore
#else
        public List<int?> AdditionalPersonIds { get; set; }
#endif
        /// <summary>The automaticallyOnboard property</summary>
        public bool? AutomaticallyOnboard { get; set; }
        /// <summary>The isDevLab property</summary>
        public bool? IsDevLab { get; set; }
        /// <summary>The onboardingCorrelationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnboardingCorrelationId { get; set; }
#nullable restore
#else
        public string OnboardingCorrelationId { get; set; }
#endif
        /// <summary>The onboardingSessionAutoConsentToReboots property</summary>
        public bool? OnboardingSessionAutoConsentToReboots { get; set; }
        /// <summary>The string or integer value may be used. Reboot = 0, Suppress = 1, FailSession = 2</summary>
        public global::Bezalu.ImmyBot.Client.Models.PromptTimeoutAction? OnboardingSessionPromptTimeoutAction { get; set; }
        /// <summary>The onboardingSessionPromptTimeoutMinutes property</summary>
        public int? OnboardingSessionPromptTimeoutMinutes { get; set; }
        /// <summary>The string or integer value may be used. Normal = 0, Suppress = 1, Prompt = 2, Force = -1</summary>
        public global::Bezalu.ImmyBot.Client.Models.RebootPreference? OnboardingSessionRebootPreference { get; set; }
        /// <summary>The onboardingSessionSendFollowUpEmail property</summary>
        public bool? OnboardingSessionSendFollowUpEmail { get; set; }
        /// <summary>The primaryPersonId property</summary>
        public int? PrimaryPersonId { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalPersonIds", n => { AdditionalPersonIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "automaticallyOnboard", n => { AutomaticallyOnboard = n.GetBoolValue(); } },
                { "isDevLab", n => { IsDevLab = n.GetBoolValue(); } },
                { "onboardingCorrelationId", n => { OnboardingCorrelationId = n.GetStringValue(); } },
                { "onboardingSessionAutoConsentToReboots", n => { OnboardingSessionAutoConsentToReboots = n.GetBoolValue(); } },
                { "onboardingSessionPromptTimeoutAction", n => { OnboardingSessionPromptTimeoutAction = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.PromptTimeoutAction>(); } },
                { "onboardingSessionPromptTimeoutMinutes", n => { OnboardingSessionPromptTimeoutMinutes = n.GetIntValue(); } },
                { "onboardingSessionRebootPreference", n => { OnboardingSessionRebootPreference = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.RebootPreference>(); } },
                { "onboardingSessionSendFollowUpEmail", n => { OnboardingSessionSendFollowUpEmail = n.GetBoolValue(); } },
                { "primaryPersonId", n => { PrimaryPersonId = n.GetIntValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("additionalPersonIds", AdditionalPersonIds);
            writer.WriteBoolValue("automaticallyOnboard", AutomaticallyOnboard);
            writer.WriteBoolValue("isDevLab", IsDevLab);
            writer.WriteStringValue("onboardingCorrelationId", OnboardingCorrelationId);
            writer.WriteBoolValue("onboardingSessionAutoConsentToReboots", OnboardingSessionAutoConsentToReboots);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.PromptTimeoutAction>("onboardingSessionPromptTimeoutAction", OnboardingSessionPromptTimeoutAction);
            writer.WriteIntValue("onboardingSessionPromptTimeoutMinutes", OnboardingSessionPromptTimeoutMinutes);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.RebootPreference>("onboardingSessionRebootPreference", OnboardingSessionRebootPreference);
            writer.WriteBoolValue("onboardingSessionSendFollowUpEmail", OnboardingSessionSendFollowUpEmail);
            writer.WriteIntValue("primaryPersonId", PrimaryPersonId);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
