// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentInstallationDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The detectedInstalledVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectedInstalledVersion { get; set; }
#nullable restore
#else
        public string DetectedInstalledVersion { get; set; }
#endif
        /// <summary>The isApplicationRegistryEntryPresent property</summary>
        public bool? IsApplicationRegistryEntryPresent { get; set; }
        /// <summary>The isServicePresent property</summary>
        public bool? IsServicePresent { get; set; }
        /// <summary>The isServiceRunning property</summary>
        public bool? IsServiceRunning { get; set; }
        /// <summary>The runningBinaryVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunningBinaryVersion { get; set; }
#nullable restore
#else
        public string RunningBinaryVersion { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AgentInstallationDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AgentInstallationDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AgentInstallationDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "detectedInstalledVersion", n => { DetectedInstalledVersion = n.GetStringValue(); } },
                { "isApplicationRegistryEntryPresent", n => { IsApplicationRegistryEntryPresent = n.GetBoolValue(); } },
                { "isServicePresent", n => { IsServicePresent = n.GetBoolValue(); } },
                { "isServiceRunning", n => { IsServiceRunning = n.GetBoolValue(); } },
                { "runningBinaryVersion", n => { RunningBinaryVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("detectedInstalledVersion", DetectedInstalledVersion);
            writer.WriteBoolValue("isApplicationRegistryEntryPresent", IsApplicationRegistryEntryPresent);
            writer.WriteBoolValue("isServicePresent", IsServicePresent);
            writer.WriteBoolValue("isServiceRunning", IsServiceRunning);
            writer.WriteStringValue("runningBinaryVersion", RunningBinaryVersion);
        }
    }
}
#pragma warning restore CS0618
