// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthorizationDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The authorizedViewerTenants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AuthorizedViewerTenants { get; set; }
#nullable restore
#else
        public List<int?> AuthorizedViewerTenants { get; set; }
#endif
        /// <summary>The ownerTenantId property</summary>
        public int? OwnerTenantId { get; set; }
        /// <summary>The ownerTenantName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerTenantName { get; set; }
#nullable restore
#else
        public string OwnerTenantName { get; set; }
#endif
        /// <summary>The visibleToAllTenants property</summary>
        public bool? VisibleToAllTenants { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AuthorizationDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AuthorizationDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AuthorizationDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authorizedViewerTenants", n => { AuthorizedViewerTenants = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "ownerTenantId", n => { OwnerTenantId = n.GetIntValue(); } },
                { "ownerTenantName", n => { OwnerTenantName = n.GetStringValue(); } },
                { "visibleToAllTenants", n => { VisibleToAllTenants = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("authorizedViewerTenants", AuthorizedViewerTenants);
            writer.WriteIntValue("ownerTenantId", OwnerTenantId);
            writer.WriteStringValue("ownerTenantName", OwnerTenantName);
            writer.WriteBoolValue("visibleToAllTenants", VisibleToAllTenants);
        }
    }
}
#pragma warning restore CS0618
