// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Partner = 1, Customer = 2, Standalone = 3</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AzTenantType
    {
        [EnumMember(Value = "Partner")]
        #pragma warning disable CS1591
        Partner,
        #pragma warning restore CS1591
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Standalone")]
        #pragma warning disable CS1591
        Standalone,
        #pragma warning restore CS1591
    }
}
