// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AzureTenantResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The string or integer value may be used. Partner = 1, Customer = 2, Standalone = 3</summary>
        public global::Bezalu.ImmyBot.Client.Models.AzTenantType? AzureTenantType { get; set; }
        /// <summary>The consentDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails? ConsentDetails { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails ConsentDetails { get; set; }
#endif
        /// <summary>The infoSyncedFromAzure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AzureTenantInfo? InfoSyncedFromAzure { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AzureTenantInfo InfoSyncedFromAzure { get; set; }
#endif
        /// <summary>The lastGetTenantInfoSyncResult property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AzureSyncResult? LastGetTenantInfoSyncResult { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AzureSyncResult LastGetTenantInfoSyncResult { get; set; }
#endif
        /// <summary>The lastGetUsersSyncResult property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AzureSyncResult? LastGetUsersSyncResult { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AzureSyncResult LastGetUsersSyncResult { get; set; }
#endif
        /// <summary>The partnerPrincipalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartnerPrincipalId { get; set; }
#nullable restore
#else
        public string PartnerPrincipalId { get; set; }
#endif
        /// <summary>The principalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrincipalId { get; set; }
#nullable restore
#else
        public string PrincipalId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AzureTenantResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AzureTenantResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AzureTenantResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "azureTenantType", n => { AzureTenantType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.AzTenantType>(); } },
                { "consentDetails", n => { ConsentDetails = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails>(global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails.CreateFromDiscriminatorValue); } },
                { "infoSyncedFromAzure", n => { InfoSyncedFromAzure = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureTenantInfo>(global::Bezalu.ImmyBot.Client.Models.AzureTenantInfo.CreateFromDiscriminatorValue); } },
                { "lastGetTenantInfoSyncResult", n => { LastGetTenantInfoSyncResult = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureSyncResult>(global::Bezalu.ImmyBot.Client.Models.AzureSyncResult.CreateFromDiscriminatorValue); } },
                { "lastGetUsersSyncResult", n => { LastGetUsersSyncResult = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureSyncResult>(global::Bezalu.ImmyBot.Client.Models.AzureSyncResult.CreateFromDiscriminatorValue); } },
                { "partnerPrincipalId", n => { PartnerPrincipalId = n.GetStringValue(); } },
                { "principalId", n => { PrincipalId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.AzTenantType>("azureTenantType", AzureTenantType);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails>("consentDetails", ConsentDetails);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureTenantInfo>("infoSyncedFromAzure", InfoSyncedFromAzure);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureSyncResult>("lastGetTenantInfoSyncResult", LastGetTenantInfoSyncResult);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureSyncResult>("lastGetUsersSyncResult", LastGetUsersSyncResult);
            writer.WriteStringValue("partnerPrincipalId", PartnerPrincipalId);
            writer.WriteStringValue("principalId", PrincipalId);
        }
    }
}
#pragma warning restore CS0618
