// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AzureTenantConsentDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The consentDateUtc property</summary>
        public DateTimeOffset? ConsentDateUtc { get; set; }
        /// <summary>The string or integer value may be used. Backend = 0, Custom = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.AppRegistrationType? ConsentedWith { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AzureTenantConsentDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "consentDateUtc", n => { ConsentDateUtc = n.GetDateTimeOffsetValue(); } },
                { "consentedWith", n => { ConsentedWith = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.AppRegistrationType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("consentDateUtc", ConsentDateUtc);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.AppRegistrationType>("consentedWith", ConsentedWith);
        }
    }
}
#pragma warning restore CS0618
