// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AzureTenantCustomerICollectionAzureErrorOneOf : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The asT0 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomer>? AsT0 { get; private set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomer> AsT0 { get; private set; }
#endif
        /// <summary>The asT1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AzureError? AsT1 { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AzureError AsT1 { get; set; }
#endif
        /// <summary>The index property</summary>
        public int? Index { get; private set; }
        /// <summary>The isT0 property</summary>
        public bool? IsT0 { get; private set; }
        /// <summary>The isT1 property</summary>
        public bool? IsT1 { get; private set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Value { get; private set; }
#nullable restore
#else
        public UntypedNode Value { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomerICollectionAzureErrorOneOf"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomerICollectionAzureErrorOneOf CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomerICollectionAzureErrorOneOf();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asT0", n => { AsT0 = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomer>(global::Bezalu.ImmyBot.Client.Models.AzureTenantCustomer.CreateFromDiscriminatorValue)?.AsList(); } },
                { "asT1", n => { AsT1 = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureError>(global::Bezalu.ImmyBot.Client.Models.AzureError.CreateFromDiscriminatorValue); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "isT0", n => { IsT0 = n.GetBoolValue(); } },
                { "isT1", n => { IsT1 = n.GetBoolValue(); } },
                { "value", n => { Value = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AzureError>("asT1", AsT1);
        }
    }
}
#pragma warning restore CS0618
