// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingSubscription : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The billingPeriodUnit property</summary>
        public long? BillingPeriodUnit { get; set; }
        /// <summary>The cancelledAt property</summary>
        public DateTimeOffset? CancelledAt { get; set; }
        /// <summary>The currencyCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The nextBillingAt property</summary>
        public DateTimeOffset? NextBillingAt { get; set; }
        /// <summary>The subscriptionItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.BillingSubscriptionItem>? SubscriptionItems { get; set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.BillingSubscriptionItem> SubscriptionItems { get; set; }
#endif
        /// <summary>The totalDues property</summary>
        public long? TotalDues { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.BillingSubscription"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.BillingSubscription CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.BillingSubscription();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingPeriodUnit", n => { BillingPeriodUnit = n.GetLongValue(); } },
                { "cancelledAt", n => { CancelledAt = n.GetDateTimeOffsetValue(); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "nextBillingAt", n => { NextBillingAt = n.GetDateTimeOffsetValue(); } },
                { "subscriptionItems", n => { SubscriptionItems = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.BillingSubscriptionItem>(global::Bezalu.ImmyBot.Client.Models.BillingSubscriptionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalDues", n => { TotalDues = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("billingPeriodUnit", BillingPeriodUnit);
            writer.WriteDateTimeOffsetValue("cancelledAt", CancelledAt);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteDateTimeOffsetValue("nextBillingAt", NextBillingAt);
            writer.WriteCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.BillingSubscriptionItem>("subscriptionItems", SubscriptionItems);
            writer.WriteLongValue("totalDues", TotalDues);
        }
    }
}
#pragma warning restore CS0618
