// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. UnKnown = 0, Visa = 1, Mastercard = 2, AmericanExpress = 3, Discover = 4, Jcb = 5, DinersClub = 6, Other = 7, Bancontact = 8, CmrFalabella = 9, TarjetaNaranja = 10, Nativa = 11, Cencosud = 12, Cabal = 13, Argencard = 14, Elo = 15, Hipercard = 16, Carnet = 17, Rupay = 18, Maestro = 19, Dankort = 20, CartesBancaires = 21, NotApplicable = 22</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BrandEnum
    {
        [EnumMember(Value = "UnKnown")]
        #pragma warning disable CS1591
        UnKnown,
        #pragma warning restore CS1591
        [EnumMember(Value = "Visa")]
        #pragma warning disable CS1591
        Visa,
        #pragma warning restore CS1591
        [EnumMember(Value = "Mastercard")]
        #pragma warning disable CS1591
        Mastercard,
        #pragma warning restore CS1591
        [EnumMember(Value = "AmericanExpress")]
        #pragma warning disable CS1591
        AmericanExpress,
        #pragma warning restore CS1591
        [EnumMember(Value = "Discover")]
        #pragma warning disable CS1591
        Discover,
        #pragma warning restore CS1591
        [EnumMember(Value = "Jcb")]
        #pragma warning disable CS1591
        Jcb,
        #pragma warning restore CS1591
        [EnumMember(Value = "DinersClub")]
        #pragma warning disable CS1591
        DinersClub,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bancontact")]
        #pragma warning disable CS1591
        Bancontact,
        #pragma warning restore CS1591
        [EnumMember(Value = "CmrFalabella")]
        #pragma warning disable CS1591
        CmrFalabella,
        #pragma warning restore CS1591
        [EnumMember(Value = "TarjetaNaranja")]
        #pragma warning disable CS1591
        TarjetaNaranja,
        #pragma warning restore CS1591
        [EnumMember(Value = "Nativa")]
        #pragma warning disable CS1591
        Nativa,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cencosud")]
        #pragma warning disable CS1591
        Cencosud,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cabal")]
        #pragma warning disable CS1591
        Cabal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Argencard")]
        #pragma warning disable CS1591
        Argencard,
        #pragma warning restore CS1591
        [EnumMember(Value = "Elo")]
        #pragma warning disable CS1591
        Elo,
        #pragma warning restore CS1591
        [EnumMember(Value = "Hipercard")]
        #pragma warning disable CS1591
        Hipercard,
        #pragma warning restore CS1591
        [EnumMember(Value = "Carnet")]
        #pragma warning disable CS1591
        Carnet,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rupay")]
        #pragma warning disable CS1591
        Rupay,
        #pragma warning restore CS1591
        [EnumMember(Value = "Maestro")]
        #pragma warning disable CS1591
        Maestro,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dankort")]
        #pragma warning disable CS1591
        Dankort,
        #pragma warning restore CS1591
        [EnumMember(Value = "CartesBancaires")]
        #pragma warning disable CS1591
        CartesBancaires,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotApplicable")]
        #pragma warning disable CS1591
        NotApplicable,
        #pragma warning restore CS1591
    }
}
