// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BulkCreateTenantRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ownerTenantId property</summary>
        public int? OwnerTenantId { get; set; }
        /// <summary>The tenants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBodyListItem>? Tenants { get; set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBodyListItem> Tenants { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ownerTenantId", n => { OwnerTenantId = n.GetIntValue(); } },
                { "tenants", n => { Tenants = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBodyListItem>(global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBodyListItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("ownerTenantId", OwnerTenantId);
            writer.WriteCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.BulkCreateTenantRequestBodyListItem>("tenants", Tenants);
        }
    }
}
#pragma warning restore CS0618
