// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. WaitingForApproval = 1, Denied = 2, ApprovedAndApplied = 3, NeedsAttention = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChangeRequestState
    {
        [EnumMember(Value = "WaitingForApproval")]
        #pragma warning disable CS1591
        WaitingForApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "Denied")]
        #pragma warning disable CS1591
        Denied,
        #pragma warning restore CS1591
        [EnumMember(Value = "ApprovedAndApplied")]
        #pragma warning disable CS1591
        ApprovedAndApplied,
        #pragma warning restore CS1591
        [EnumMember(Value = "NeedsAttention")]
        #pragma warning disable CS1591
        NeedsAttention,
        #pragma warning restore CS1591
    }
}
