// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Paid = 0, Posted = 1, PaymentDue = 2, NotPaid = 3, Voided = 4, Pending = 5, Unknown = 6</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChargebeeInvoiceStatus
    {
        [EnumMember(Value = "Paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
        [EnumMember(Value = "Posted")]
        #pragma warning disable CS1591
        Posted,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentDue")]
        #pragma warning disable CS1591
        PaymentDue,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotPaid")]
        #pragma warning disable CS1591
        NotPaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "Voided")]
        #pragma warning disable CS1591
        Voided,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
