// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CircuitBreakerState : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The circuitState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CircuitState { get; set; }
#nullable restore
#else
        public string CircuitState { get; set; }
#endif
        /// <summary>The lastException property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.ExceptionObject? LastException { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.ExceptionObject LastException { get; set; }
#endif
        /// <summary>The policyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyName { get; set; }
#nullable restore
#else
        public string PolicyName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.CircuitBreakerState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.CircuitBreakerState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.CircuitBreakerState();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "circuitState", n => { CircuitState = n.GetStringValue(); } },
                { "lastException", n => { LastException = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.ExceptionObject>(global::Bezalu.ImmyBot.Client.Models.ExceptionObject.CreateFromDiscriminatorValue); } },
                { "policyName", n => { PolicyName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("circuitState", CircuitState);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.ExceptionObject>("lastException", LastException);
            writer.WriteStringValue("policyName", PolicyName);
        }
    }
}
#pragma warning restore CS0618
