// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Skip = 1, ApplyOnConnect = 2</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComputerOfflineMaintenanceSessionBehavior
    {
        [EnumMember(Value = "Skip")]
        #pragma warning disable CS1591
        Skip,
        #pragma warning restore CS1591
        [EnumMember(Value = "ApplyOnConnect")]
        #pragma warning disable CS1591
        ApplyOnConnect,
        #pragma warning restore CS1591
    }
}
