// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContributingRoleAssignment : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assignment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.UserRoleAssignmentDto? Assignment { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.UserRoleAssignmentDto Assignment { get; set; }
#endif
        /// <summary>The assignmentScopeDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentScopeDescription { get; set; }
#nullable restore
#else
        public string AssignmentScopeDescription { get; set; }
#endif
        /// <summary>The isBuiltIn property</summary>
        public bool? IsBuiltIn { get; set; }
        /// <summary>The isWinning property</summary>
        public bool? IsWinning { get; set; }
        /// <summary>The overrideReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OverrideReason { get; set; }
#nullable restore
#else
        public string OverrideReason { get; set; }
#endif
        /// <summary>The precedenceLevel property</summary>
        public int? PrecedenceLevel { get; set; }
        /// <summary>The roleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoleName { get; set; }
#nullable restore
#else
        public string RoleName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.ContributingRoleAssignment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.ContributingRoleAssignment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.ContributingRoleAssignment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignment", n => { Assignment = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.UserRoleAssignmentDto>(global::Bezalu.ImmyBot.Client.Models.UserRoleAssignmentDto.CreateFromDiscriminatorValue); } },
                { "assignmentScopeDescription", n => { AssignmentScopeDescription = n.GetStringValue(); } },
                { "isBuiltIn", n => { IsBuiltIn = n.GetBoolValue(); } },
                { "isWinning", n => { IsWinning = n.GetBoolValue(); } },
                { "overrideReason", n => { OverrideReason = n.GetStringValue(); } },
                { "precedenceLevel", n => { PrecedenceLevel = n.GetIntValue(); } },
                { "roleName", n => { RoleName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.UserRoleAssignmentDto>("assignment", Assignment);
            writer.WriteStringValue("assignmentScopeDescription", AssignmentScopeDescription);
            writer.WriteBoolValue("isBuiltIn", IsBuiltIn);
            writer.WriteBoolValue("isWinning", IsWinning);
            writer.WriteStringValue("overrideReason", OverrideReason);
            writer.WriteIntValue("precedenceLevel", PrecedenceLevel);
            writer.WriteStringValue("roleName", RoleName);
        }
    }
}
#pragma warning restore CS0618
