// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. SoftwareTable = 0, CustomDetectionScript = 1, UpgradeCode = 2, ProductCode = 3</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DetectionMethod
    {
        [EnumMember(Value = "SoftwareTable")]
        #pragma warning disable CS1591
        SoftwareTable,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomDetectionScript")]
        #pragma warning disable CS1591
        CustomDetectionScript,
        #pragma warning restore CS1591
        [EnumMember(Value = "UpgradeCode")]
        #pragma warning disable CS1591
        UpgradeCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProductCode")]
        #pragma warning disable CS1591
        ProductCode,
        #pragma warning restore CS1591
    }
}
