// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeviceDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The azureTenantId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AzureTenantId { get; set; }
#nullable restore
#else
        public string AzureTenantId { get; set; }
#endif
        /// <summary>The chassisTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? ChassisTypes { get; set; }
#nullable restore
#else
        public List<int?> ChassisTypes { get; set; }
#endif
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The deviceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The domainRole property</summary>
        public int? DomainRole { get; set; }
        /// <summary>The isSandbox property</summary>
        public bool? IsSandbox { get; set; }
        /// <summary>The machineId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineId { get; set; }
#nullable restore
#else
        public string MachineId { get; set; }
#endif
        /// <summary>The manufacturer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Manufacturer { get; set; }
#nullable restore
#else
        public string Manufacturer { get; set; }
#endif
        /// <summary>The operatingSystemName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperatingSystemName { get; set; }
#nullable restore
#else
        public string OperatingSystemName { get; set; }
#endif
        /// <summary>The osInstallDateUTC property</summary>
        public DateTimeOffset? OsInstallDateUTC { get; set; }
        /// <summary>The serialNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SerialNumber { get; set; }
#nullable restore
#else
        public string SerialNumber { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.DeviceDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.DeviceDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.DeviceDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "azureTenantId", n => { AzureTenantId = n.GetStringValue(); } },
                { "chassisTypes", n => { ChassisTypes = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "domainRole", n => { DomainRole = n.GetIntValue(); } },
                { "isSandbox", n => { IsSandbox = n.GetBoolValue(); } },
                { "machineId", n => { MachineId = n.GetStringValue(); } },
                { "manufacturer", n => { Manufacturer = n.GetStringValue(); } },
                { "operatingSystemName", n => { OperatingSystemName = n.GetStringValue(); } },
                { "osInstallDateUTC", n => { OsInstallDateUTC = n.GetDateTimeOffsetValue(); } },
                { "serialNumber", n => { SerialNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("azureTenantId", AzureTenantId);
            writer.WriteCollectionOfPrimitiveValues<int?>("chassisTypes", ChassisTypes);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteStringValue("domain", Domain);
            writer.WriteIntValue("domainRole", DomainRole);
            writer.WriteBoolValue("isSandbox", IsSandbox);
            writer.WriteStringValue("machineId", MachineId);
            writer.WriteStringValue("manufacturer", Manufacturer);
            writer.WriteStringValue("operatingSystemName", OperatingSystemName);
            writer.WriteDateTimeOffsetValue("osInstallDateUTC", OsInstallDateUTC);
            writer.WriteStringValue("serialNumber", SerialNumber);
        }
    }
}
#pragma warning restore CS0618
