// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DynamicFormBindResult : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bindErrors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult_bindErrors? BindErrors { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult_bindErrors BindErrors { get; set; }
#endif
        /// <summary>The hasErrors property</summary>
        public bool? HasErrors { get; private set; }
        /// <summary>The parameterSetName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParameterSetName { get; set; }
#nullable restore
#else
        public string ParameterSetName { get; set; }
#endif
        /// <summary>The showCommandInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.ShowCommandInfo? ShowCommandInfo { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.ShowCommandInfo ShowCommandInfo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bindErrors", n => { BindErrors = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult_bindErrors>(global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult_bindErrors.CreateFromDiscriminatorValue); } },
                { "hasErrors", n => { HasErrors = n.GetBoolValue(); } },
                { "parameterSetName", n => { ParameterSetName = n.GetStringValue(); } },
                { "showCommandInfo", n => { ShowCommandInfo = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.ShowCommandInfo>(global::Bezalu.ImmyBot.Client.Models.ShowCommandInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.DynamicFormBindResult_bindErrors>("bindErrors", BindErrors);
            writer.WriteStringValue("parameterSetName", ParameterSetName);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.ShowCommandInfo>("showCommandInfo", ShowCommandInfo);
        }
    }
}
#pragma warning restore CS0618
