// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. OneHour = 1, OneDay = 2, Indefinite = 3, ThreeDays = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExpirationTime
    {
        [EnumMember(Value = "OneHour")]
        #pragma warning disable CS1591
        OneHour,
        #pragma warning restore CS1591
        [EnumMember(Value = "OneDay")]
        #pragma warning disable CS1591
        OneDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "Indefinite")]
        #pragma warning disable CS1591
        Indefinite,
        #pragma warning restore CS1591
        [EnumMember(Value = "ThreeDays")]
        #pragma warning disable CS1591
        ThreeDays,
        #pragma warning restore CS1591
    }
}
