// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Legacy = 0, Optimized = 1</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FilterScriptMode
    {
        [EnumMember(Value = "Legacy")]
        #pragma warning disable CS1591
        Legacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "Optimized")]
        #pragma warning disable CS1591
        Optimized,
        #pragma warning restore CS1591
    }
}
