// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetLatestActionForComputer : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The string or integer value may be used. NoAction = 0, Install = 1, Update = 2, Uninstall = 3, Download = 4, Reinstall = 5, Downgrade = 6, Undetermined = 7, TaskEnforce = 8, TaskMonitor = 9, TaskAudit = 10</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionType? ActionType { get; set; }
        /// <summary>The assignmentId property</summary>
        public int? AssignmentId { get; set; }
        /// <summary>The string or integer value may be used. Global = 0, Local = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.DatabaseType? AssignmentType { get; set; }
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The string or integer value may be used. NewerOrEqualVersion = 0, NotPresent = 1, AnyVersion = 2, ThisVersion = 3, OlderOrEqualVersion = 4, LatestVersion = 5, NoAction = 6, UpdateIfFound = 7</summary>
        public global::Bezalu.ImmyBot.Client.Models.DesiredSoftwareState? DesiredSoftwareState { get; set; }
        /// <summary>The desiredVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DesiredVersion { get; set; }
#nullable restore
#else
        public string DesiredVersion { get; set; }
#endif
        /// <summary>The detectedVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectedVersion { get; set; }
#nullable restore
#else
        public string DetectedVersion { get; set; }
#endif
        /// <summary>The endTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The maintenanceDisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintenanceDisplayName { get; set; }
#nullable restore
#else
        public string MaintenanceDisplayName { get; set; }
#endif
        /// <summary>The maintenanceIdentifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintenanceIdentifier { get; set; }
#nullable restore
#else
        public string MaintenanceIdentifier { get; set; }
#endif
        /// <summary>The maintenanceSessionId property</summary>
        public int? MaintenanceSessionId { get; set; }
        /// <summary>The string or integer value may be used. Enforce = 0, Audit = 1, Monitor = 2, NoAction = 3</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceTaskMode? MaintenanceTaskMode { get; set; }
        /// <summary>The string or integer value may be used. GlobalSoftware = 0, LocalSoftware = 1, WindowsUpdate = 2, ChocolateySoftware = 3, NiniteSoftware = 4, LocalMaintenanceTask = 5, GlobalMaintenanceTask = 6, AgentUpdate = 7</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceType? MaintenanceType { get; set; }
        /// <summary>The policyDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyDescription { get; set; }
#nullable restore
#else
        public string PolicyDescription { get; set; }
#endif
        /// <summary>The string or integer value may be used. SoftwareMissing = 0, UpdateAvailable = 1, UpToDate = 2, NotAssigned = 3, TestFailed = 4, SoftwareDetected = 5, OlderVersionRequired = 6, NoApplicableSoftwareVersion = 7, NoAction = 8, Undetermined = 9, TaskEnforce = 10, TaskAudit = 11, TaskMonitor = 12, TaskNotCompliant = 13, TaskCompliant = 14, DeviceOffline = 15, RepairTriggered = 16</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionReason? Reason { get; set; }
        /// <summary>The string or integer value may be used. Pending = 0, Success = 1, Failed = 2, Cancelled = 3, Indeterminable = 4, Resolved = 5</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResult? Result { get; set; }
        /// <summary>The string or integer value may be used. NoLicenseAvailable = 0, SoftwareNotFound = 1, DetectionActionFailed = 2, TaskNotFound = 3, TaskNotCompliant = 4, TaskCompliant = 5, TaskSetIsMissing = 6, TaskTestIsMissing = 7, TaskGetIsMissing = 8, SoftwareConfigurationTaskMissing = 9, TaskModeIsMissing = 10, DeviceOffline = 11, RebootsSuppressed = 12</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResultReason? ResultReason { get; set; }
        /// <summary>The softwareActionIdForConfigurationTask property</summary>
        public int? SoftwareActionIdForConfigurationTask { get; set; }
        /// <summary>The startTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The string or integer value may be used. NotStarted = 0, Downloading = 1, PerformingAction = 2, DeterminingResult = 3, Complete = 4, WaitingForPrerequisite = 5, DeterminingAction = 6, Skipped = 7, PendingExecution = 8</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetLatestActionForComputer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetLatestActionForComputer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetLatestActionForComputer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionType", n => { ActionType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionType>(); } },
                { "assignmentId", n => { AssignmentId = n.GetIntValue(); } },
                { "assignmentType", n => { AssignmentType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "desiredSoftwareState", n => { DesiredSoftwareState = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DesiredSoftwareState>(); } },
                { "desiredVersion", n => { DesiredVersion = n.GetStringValue(); } },
                { "detectedVersion", n => { DetectedVersion = n.GetStringValue(); } },
                { "endTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "maintenanceDisplayName", n => { MaintenanceDisplayName = n.GetStringValue(); } },
                { "maintenanceIdentifier", n => { MaintenanceIdentifier = n.GetStringValue(); } },
                { "maintenanceSessionId", n => { MaintenanceSessionId = n.GetIntValue(); } },
                { "maintenanceTaskMode", n => { MaintenanceTaskMode = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceTaskMode>(); } },
                { "maintenanceType", n => { MaintenanceType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceType>(); } },
                { "policyDescription", n => { PolicyDescription = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionReason>(); } },
                { "result", n => { Result = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResult>(); } },
                { "resultReason", n => { ResultReason = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResultReason>(); } },
                { "softwareActionIdForConfigurationTask", n => { SoftwareActionIdForConfigurationTask = n.GetIntValue(); } },
                { "startTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionType>("actionType", ActionType);
            writer.WriteIntValue("assignmentId", AssignmentId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>("assignmentType", AssignmentType);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DesiredSoftwareState>("desiredSoftwareState", DesiredSoftwareState);
            writer.WriteStringValue("desiredVersion", DesiredVersion);
            writer.WriteStringValue("detectedVersion", DetectedVersion);
            writer.WriteDateTimeOffsetValue("endTime", EndTime);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("maintenanceDisplayName", MaintenanceDisplayName);
            writer.WriteStringValue("maintenanceIdentifier", MaintenanceIdentifier);
            writer.WriteIntValue("maintenanceSessionId", MaintenanceSessionId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceTaskMode>("maintenanceTaskMode", MaintenanceTaskMode);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceType>("maintenanceType", MaintenanceType);
            writer.WriteStringValue("policyDescription", PolicyDescription);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionReason>("reason", Reason);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResult>("result", Result);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionResultReason>("resultReason", ResultReason);
            writer.WriteIntValue("softwareActionIdForConfigurationTask", SoftwareActionIdForConfigurationTask);
            writer.WriteDateTimeOffsetValue("startTime", StartTime);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
