// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetMaintenanceSessionPhaseResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The string or integer value may be used. DetectInstalledAgentVersion = 0, UpdateAgentVersion = 1, VerifyAgentVersionUpdated = 2, DetectInstalledVersion = 200, DetermineDesiredVersion = 201, TestSoftware = 202, CheckForSoftwareLicense = 203, AddConfigTask = 204, TestTask = 205, MonitorTask = 206, AuditTask = 207, FetchDesiredVersion = 301, EnforceTask = 302, ApplyWindowsPatch = 305, DownloadConfigTaskFiles = 306, FetchDependentVersion = 307, InstallDependentVersion = 308, InstallSoftware = 309, RunUpgradeSoftwareScript = 310, UninstallSoftware = 311, RepairSoftware = 313, DownloadInstaller = 314, PostUninstallSoftware = 315, PostInstallSoftware = 316, TestTaskBeforeExecution = 317, TestSoftwareAfterExecution = 318, VerifyTask = 319, VerifySoftwareIsInDesiredState = 320</summary>
        public global::Bezalu.ImmyBot.Client.Models.ActionProgressPhaseName? ActionProgressPhaseName { get; set; }
        /// <summary>The dateCompletedUtc property</summary>
        public DateTimeOffset? DateCompletedUtc { get; set; }
        /// <summary>The dateStartedUtc property</summary>
        public DateTimeOffset? DateStartedUtc { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The maintenanceActionId property</summary>
        public int? MaintenanceActionId { get; set; }
        /// <summary>The maintenanceSessionId property</summary>
        public int? MaintenanceSessionId { get; set; }
        /// <summary>The maintenanceSessionStageId property</summary>
        public int? MaintenanceSessionStageId { get; set; }
        /// <summary>The phaseName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhaseName { get; set; }
#nullable restore
#else
        public string PhaseName { get; set; }
#endif
        /// <summary>The progressCompleted property</summary>
        public bool? ProgressCompleted { get; set; }
        /// <summary>The progressPercentComplete property</summary>
        public double? ProgressPercentComplete { get; set; }
        /// <summary>The progressStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgressStatus { get; set; }
#nullable restore
#else
        public string ProgressStatus { get; set; }
#endif
        /// <summary>The string or integer value may be used. Unstarted = 0, Skipped = 1, Running = 2, Succeeded = 3, Failed = 4</summary>
        public global::Bezalu.ImmyBot.Client.Models.SessionPhaseStatus? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionPhaseResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionPhaseResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionPhaseResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionProgressPhaseName", n => { ActionProgressPhaseName = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ActionProgressPhaseName>(); } },
                { "dateCompletedUtc", n => { DateCompletedUtc = n.GetDateTimeOffsetValue(); } },
                { "dateStartedUtc", n => { DateStartedUtc = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "maintenanceActionId", n => { MaintenanceActionId = n.GetIntValue(); } },
                { "maintenanceSessionId", n => { MaintenanceSessionId = n.GetIntValue(); } },
                { "maintenanceSessionStageId", n => { MaintenanceSessionStageId = n.GetIntValue(); } },
                { "phaseName", n => { PhaseName = n.GetStringValue(); } },
                { "progressCompleted", n => { ProgressCompleted = n.GetBoolValue(); } },
                { "progressPercentComplete", n => { ProgressPercentComplete = n.GetDoubleValue(); } },
                { "progressStatus", n => { ProgressStatus = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionPhaseStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ActionProgressPhaseName>("actionProgressPhaseName", ActionProgressPhaseName);
            writer.WriteDateTimeOffsetValue("dateCompletedUtc", DateCompletedUtc);
            writer.WriteDateTimeOffsetValue("dateStartedUtc", DateStartedUtc);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("maintenanceActionId", MaintenanceActionId);
            writer.WriteIntValue("maintenanceSessionId", MaintenanceSessionId);
            writer.WriteIntValue("maintenanceSessionStageId", MaintenanceSessionStageId);
            writer.WriteStringValue("phaseName", PhaseName);
            writer.WriteBoolValue("progressCompleted", ProgressCompleted);
            writer.WriteDoubleValue("progressPercentComplete", ProgressPercentComplete);
            writer.WriteStringValue("progressStatus", ProgressStatus);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionPhaseStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
