// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetMaintenanceSessionStageResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdBy property</summary>
        public int? CreatedBy { get; set; }
        /// <summary>The createdDateUTC property</summary>
        public DateTimeOffset? CreatedDateUTC { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; private set; }
        /// <summary>The jobId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobId { get; private set; }
#nullable restore
#else
        public string JobId { get; private set; }
#endif
        /// <summary>The maintenanceSession property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse? MaintenanceSession { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse MaintenanceSession { get; set; }
#endif
        /// <summary>The maintenanceSessionId property</summary>
        public int? MaintenanceSessionId { get; private set; }
        /// <summary>The string or integer value may be used. Passed = 0, Running = 1, Failed = 2, Created = 3, Cancelled = 4, Postponed = 5, Pending = 6, PartialPassed = 7, PendingConnectivity = 8, Missed = 9, MaxTrackedDevicesPerMonthExceeded = 10, PendingPreflight = 11, PendingEphemeralAgentConnection = 12, MaintenanceForTrackableDevicesNotAllowed = 13, Expired = 14</summary>
        public global::Bezalu.ImmyBot.Client.Models.SessionStatus? StageStatus { get; set; }
        /// <summary>The string or integer value may be used. Onboarding = 0, Detection = 1, Execution = 2, AgentUpdates = 3, Resolution = 4, Inventory = 5</summary>
        public global::Bezalu.ImmyBot.Client.Models.SessionStageType? Type { get; set; }
        /// <summary>The updatedBy property</summary>
        public int? UpdatedBy { get; set; }
        /// <summary>The updatedDateUTC property</summary>
        public DateTimeOffset? UpdatedDateUTC { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionStageResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionStageResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionStageResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetIntValue(); } },
                { "createdDateUTC", n => { CreatedDateUTC = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "jobId", n => { JobId = n.GetStringValue(); } },
                { "maintenanceSession", n => { MaintenanceSession = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse>(global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse.CreateFromDiscriminatorValue); } },
                { "maintenanceSessionId", n => { MaintenanceSessionId = n.GetIntValue(); } },
                { "stageStatus", n => { StageStatus = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionStageType>(); } },
                { "updatedBy", n => { UpdatedBy = n.GetIntValue(); } },
                { "updatedDateUTC", n => { UpdatedDateUTC = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDateUTC", CreatedDateUTC);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionResponse>("maintenanceSession", MaintenanceSession);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionStatus>("stageStatus", StageStatus);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionStageType>("type", Type);
            writer.WriteIntValue("updatedBy", UpdatedBy);
            writer.WriteDateTimeOffsetValue("updatedDateUTC", UpdatedDateUTC);
        }
    }
}
#pragma warning restore CS0618
