// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetMaintenanceSessionLogResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The displayEvents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent>? DisplayEvents { get; private set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent> DisplayEvents { get; private set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; private set; }
        /// <summary>The isPrimary property</summary>
        public bool? IsPrimary { get; private set; }
        /// <summary>The maintenanceActionId property</summary>
        public int? MaintenanceActionId { get; private set; }
        /// <summary>The string or integer value may be used. NotStarted = 0, Downloading = 1, PerformingAction = 2, DeterminingResult = 3, Complete = 4, WaitingForPrerequisite = 5, DeterminingAction = 6, Skipped = 7, PendingExecution = 8</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus? MaintenanceActionStatus { get; set; }
        /// <summary>The maintenanceSessionId property</summary>
        public int? MaintenanceSessionId { get; private set; }
        /// <summary>The maintenanceSessionStageId property</summary>
        public int? MaintenanceSessionStageId { get; private set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; private set; }
#nullable restore
#else
        public string Message { get; private set; }
#endif
        /// <summary>The paramBlockParameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_paramBlockParameters? ParamBlockParameters { get; private set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_paramBlockParameters ParamBlockParameters { get; private set; }
#endif
        /// <summary>The progressCorrelationId property</summary>
        public Guid? ProgressCorrelationId { get; set; }
        /// <summary>The script property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Script { get; private set; }
#nullable restore
#else
        public string Script { get; private set; }
#endif
        /// <summary>The string or integer value may be used. System = 0, CurrentUser = 1, Metascript = 2, CloudScript = 4</summary>
        public global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext? ScriptExecutionContext { get; set; }
        /// <summary>The scriptId property</summary>
        public int? ScriptId { get; private set; }
        /// <summary>The string or integer value may be used. CommandLine = 1, PowerShell = 2</summary>
        public global::Bezalu.ImmyBot.Client.Models.ScriptLanguage? ScriptLanguage { get; set; }
        /// <summary>The scriptParameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_scriptParameters? ScriptParameters { get; private set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_scriptParameters ScriptParameters { get; private set; }
#endif
        /// <summary>The scriptTimeout property</summary>
        public int? ScriptTimeout { get; private set; }
        /// <summary>The string or integer value may be used. Global = 0, Local = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.DatabaseType? ScriptType { get; set; }
        /// <summary>The string or integer value may be used. Generic = 0, Error = 1, Command = 2, CommandResult = 3, Progress = 4</summary>
        public global::Bezalu.ImmyBot.Client.Models.SessionLogType? SessionLogType { get; set; }
        /// <summary>The sessionPhaseId property</summary>
        public int? SessionPhaseId { get; private set; }
        /// <summary>The time property</summary>
        public DateTimeOffset? Time { get; private set; }
        /// <summary>The updatedTime property</summary>
        public DateTimeOffset? UpdatedTime { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "displayEvents", n => { DisplayEvents = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent>(global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isPrimary", n => { IsPrimary = n.GetBoolValue(); } },
                { "maintenanceActionId", n => { MaintenanceActionId = n.GetIntValue(); } },
                { "maintenanceActionStatus", n => { MaintenanceActionStatus = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus>(); } },
                { "maintenanceSessionId", n => { MaintenanceSessionId = n.GetIntValue(); } },
                { "maintenanceSessionStageId", n => { MaintenanceSessionStageId = n.GetIntValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "paramBlockParameters", n => { ParamBlockParameters = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_paramBlockParameters>(global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_paramBlockParameters.CreateFromDiscriminatorValue); } },
                { "progressCorrelationId", n => { ProgressCorrelationId = n.GetGuidValue(); } },
                { "script", n => { Script = n.GetStringValue(); } },
                { "scriptExecutionContext", n => { ScriptExecutionContext = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext>(); } },
                { "scriptId", n => { ScriptId = n.GetIntValue(); } },
                { "scriptLanguage", n => { ScriptLanguage = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptLanguage>(); } },
                { "scriptParameters", n => { ScriptParameters = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_scriptParameters>(global::Bezalu.ImmyBot.Client.Models.GetMaintenanceSessionLogResponse_scriptParameters.CreateFromDiscriminatorValue); } },
                { "scriptTimeout", n => { ScriptTimeout = n.GetIntValue(); } },
                { "scriptType", n => { ScriptType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>(); } },
                { "sessionLogType", n => { SessionLogType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionLogType>(); } },
                { "sessionPhaseId", n => { SessionPhaseId = n.GetIntValue(); } },
                { "time", n => { Time = n.GetDateTimeOffsetValue(); } },
                { "updatedTime", n => { UpdatedTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceActionStatus>("maintenanceActionStatus", MaintenanceActionStatus);
            writer.WriteGuidValue("progressCorrelationId", ProgressCorrelationId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext>("scriptExecutionContext", ScriptExecutionContext);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptLanguage>("scriptLanguage", ScriptLanguage);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>("scriptType", ScriptType);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionLogType>("sessionLogType", SessionLogType);
        }
    }
}
#pragma warning restore CS0618
