// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOptionalTargetAssignmentApprovalResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The string or integer value may be used. Pending = 1, Approved = 2, Denied = 3</summary>
        public global::Bezalu.ImmyBot.Client.Models.TargetAssignmentApprovalStatus? Approved { get; set; }
        /// <summary>The createdBy property</summary>
        public int? CreatedBy { get; set; }
        /// <summary>The createdDateUTC property</summary>
        public DateTimeOffset? CreatedDateUTC { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The string or integer value may be used. GlobalSoftware = 0, LocalSoftware = 1, WindowsUpdate = 2, ChocolateySoftware = 3, NiniteSoftware = 4, LocalMaintenanceTask = 5, GlobalMaintenanceTask = 6, AgentUpdate = 7</summary>
        public global::Bezalu.ImmyBot.Client.Models.MaintenanceType? MaintenanceType { get; set; }
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Target { get; set; }
#nullable restore
#else
        public string Target { get; set; }
#endif
        /// <summary>The targetAssignmentId property</summary>
        public int? TargetAssignmentId { get; set; }
        /// <summary>The string or integer value may be used. All = 1, Computer = 2, Metascript = 5, Person = 7, AzureGroup = 8, TenantMetascript = 20, AllForTenant = 21, ProviderDeviceGroup = 22, ProviderClientGroup = 23, TenantFilterScript = 24, FilterScript = 25, AllTenants = 28, SpecificTenant = 29, Tag = 30, TenantTag = 31, CloudTag = 40, CloudProviderClientGroup = 42</summary>
        public global::Bezalu.ImmyBot.Client.Models.TargetType? TargetType { get; set; }
        /// <summary>The updatedBy property</summary>
        public int? UpdatedBy { get; set; }
        /// <summary>The updatedDateUTC property</summary>
        public DateTimeOffset? UpdatedDateUTC { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetOptionalTargetAssignmentApprovalResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetOptionalTargetAssignmentApprovalResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetOptionalTargetAssignmentApprovalResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approved", n => { Approved = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.TargetAssignmentApprovalStatus>(); } },
                { "createdBy", n => { CreatedBy = n.GetIntValue(); } },
                { "createdDateUTC", n => { CreatedDateUTC = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "maintenanceType", n => { MaintenanceType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceType>(); } },
                { "target", n => { Target = n.GetStringValue(); } },
                { "targetAssignmentId", n => { TargetAssignmentId = n.GetIntValue(); } },
                { "targetType", n => { TargetType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.TargetType>(); } },
                { "updatedBy", n => { UpdatedBy = n.GetIntValue(); } },
                { "updatedDateUTC", n => { UpdatedDateUTC = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.TargetAssignmentApprovalStatus>("approved", Approved);
            writer.WriteIntValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDateUTC", CreatedDateUTC);
            writer.WriteIntValue("id", Id);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.MaintenanceType>("maintenanceType", MaintenanceType);
            writer.WriteStringValue("target", Target);
            writer.WriteIntValue("targetAssignmentId", TargetAssignmentId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.TargetType>("targetType", TargetType);
            writer.WriteIntValue("updatedBy", UpdatedBy);
            writer.WriteDateTimeOffsetValue("updatedDateUTC", UpdatedDateUTC);
        }
    }
}
#pragma warning restore CS0618
