// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetProviderClientResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdBy property</summary>
        public int? CreatedBy { get; set; }
        /// <summary>The createdDateUTC property</summary>
        public DateTimeOffset? CreatedDateUTC { get; set; }
        /// <summary>The externalClientId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalClientId { get; set; }
#nullable restore
#else
        public string ExternalClientId { get; set; }
#endif
        /// <summary>The externalClientName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalClientName { get; set; }
#nullable restore
#else
        public string ExternalClientName { get; set; }
#endif
        /// <summary>The internalData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? InternalData { get; set; }
#nullable restore
#else
        public UntypedNode InternalData { get; set; }
#endif
        /// <summary>The linkedToTenantId property</summary>
        public int? LinkedToTenantId { get; set; }
        /// <summary>The providerLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.GetProviderLinkResponse? ProviderLink { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.GetProviderLinkResponse ProviderLink { get; set; }
#endif
        /// <summary>The providerLinkId property</summary>
        public int? ProviderLinkId { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Types { get; set; }
#nullable restore
#else
        public List<string> Types { get; set; }
#endif
        /// <summary>The updatedBy property</summary>
        public int? UpdatedBy { get; set; }
        /// <summary>The updatedDateUTC property</summary>
        public DateTimeOffset? UpdatedDateUTC { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetProviderClientResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetProviderClientResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetProviderClientResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetIntValue(); } },
                { "createdDateUTC", n => { CreatedDateUTC = n.GetDateTimeOffsetValue(); } },
                { "externalClientId", n => { ExternalClientId = n.GetStringValue(); } },
                { "externalClientName", n => { ExternalClientName = n.GetStringValue(); } },
                { "internalData", n => { InternalData = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "linkedToTenantId", n => { LinkedToTenantId = n.GetIntValue(); } },
                { "providerLink", n => { ProviderLink = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.GetProviderLinkResponse>(global::Bezalu.ImmyBot.Client.Models.GetProviderLinkResponse.CreateFromDiscriminatorValue); } },
                { "providerLinkId", n => { ProviderLinkId = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "types", n => { Types = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updatedBy", n => { UpdatedBy = n.GetIntValue(); } },
                { "updatedDateUTC", n => { UpdatedDateUTC = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDateUTC", CreatedDateUTC);
            writer.WriteStringValue("externalClientId", ExternalClientId);
            writer.WriteStringValue("externalClientName", ExternalClientName);
            writer.WriteObjectValue<UntypedNode>("internalData", InternalData);
            writer.WriteIntValue("linkedToTenantId", LinkedToTenantId);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.GetProviderLinkResponse>("providerLink", ProviderLink);
            writer.WriteIntValue("providerLinkId", ProviderLinkId);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("types", Types);
            writer.WriteIntValue("updatedBy", UpdatedBy);
            writer.WriteDateTimeOffsetValue("updatedDateUTC", UpdatedDateUTC);
        }
    }
}
#pragma warning restore CS0618
