// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetPendingCountsResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public int? Active { get; set; }
        /// <summary>The failed property</summary>
        public int? Failed { get; set; }
        /// <summary>The manual property</summary>
        public int? Manual { get; set; }
        /// <summary>The offline property</summary>
        public int? Offline { get; set; }
        /// <summary>The recent property</summary>
        public int? Recent { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetPendingCountsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetPendingCountsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetPendingCountsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetIntValue(); } },
                { "failed", n => { Failed = n.GetIntValue(); } },
                { "manual", n => { Manual = n.GetIntValue(); } },
                { "offline", n => { Offline = n.GetIntValue(); } },
                { "recent", n => { Recent = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("active", Active);
            writer.WriteIntValue("failed", Failed);
            writer.WriteIntValue("manual", Manual);
            writer.WriteIntValue("offline", Offline);
            writer.WriteIntValue("recent", Recent);
            writer.WriteIntValue("total", Total);
        }
    }
}
#pragma warning restore CS0618
