// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetPreferencesResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The applicationPreferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.ApplicationPreferencesResponse? ApplicationPreferences { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.ApplicationPreferencesResponse ApplicationPreferences { get; set; }
#endif
        /// <summary>The tenantPreferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.TenantPreferencesResponse? TenantPreferences { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.TenantPreferencesResponse TenantPreferences { get; set; }
#endif
        /// <summary>The userPreferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.UserPreferencesResponse? UserPreferences { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.UserPreferencesResponse UserPreferences { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetPreferencesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetPreferencesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetPreferencesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applicationPreferences", n => { ApplicationPreferences = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.ApplicationPreferencesResponse>(global::Bezalu.ImmyBot.Client.Models.ApplicationPreferencesResponse.CreateFromDiscriminatorValue); } },
                { "tenantPreferences", n => { TenantPreferences = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.TenantPreferencesResponse>(global::Bezalu.ImmyBot.Client.Models.TenantPreferencesResponse.CreateFromDiscriminatorValue); } },
                { "userPreferences", n => { UserPreferences = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.UserPreferencesResponse>(global::Bezalu.ImmyBot.Client.Models.UserPreferencesResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.ApplicationPreferencesResponse>("applicationPreferences", ApplicationPreferences);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.TenantPreferencesResponse>("tenantPreferences", TenantPreferences);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.UserPreferencesResponse>("userPreferences", UserPreferences);
        }
    }
}
#pragma warning restore CS0618
