// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSupportBrandingResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The descriptionAlertMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionAlertMessage { get; set; }
#nullable restore
#else
        public string DescriptionAlertMessage { get; set; }
#endif
        /// <summary>The descriptionPlaceholderText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionPlaceholderText { get; set; }
#nullable restore
#else
        public string DescriptionPlaceholderText { get; set; }
#endif
        /// <summary>The footerMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FooterMessage { get; set; }
#nullable restore
#else
        public string FooterMessage { get; set; }
#endif
        /// <summary>The headerAlertMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderAlertMessage { get; set; }
#nullable restore
#else
        public string HeaderAlertMessage { get; set; }
#endif
        /// <summary>The providerId property</summary>
        public Guid? ProviderId { get; set; }
        /// <summary>The sessionSupportButtonTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionSupportButtonTitle { get; set; }
#nullable restore
#else
        public string SessionSupportButtonTitle { get; set; }
#endif
        /// <summary>The showSessionSupportConfirmCheckbox property</summary>
        public bool? ShowSessionSupportConfirmCheckbox { get; set; }
        /// <summary>The supportSidebarTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupportSidebarTitle { get; set; }
#nullable restore
#else
        public string SupportSidebarTitle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetSupportBrandingResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetSupportBrandingResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetSupportBrandingResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "descriptionAlertMessage", n => { DescriptionAlertMessage = n.GetStringValue(); } },
                { "descriptionPlaceholderText", n => { DescriptionPlaceholderText = n.GetStringValue(); } },
                { "footerMessage", n => { FooterMessage = n.GetStringValue(); } },
                { "headerAlertMessage", n => { HeaderAlertMessage = n.GetStringValue(); } },
                { "providerId", n => { ProviderId = n.GetGuidValue(); } },
                { "sessionSupportButtonTitle", n => { SessionSupportButtonTitle = n.GetStringValue(); } },
                { "showSessionSupportConfirmCheckbox", n => { ShowSessionSupportConfirmCheckbox = n.GetBoolValue(); } },
                { "supportSidebarTitle", n => { SupportSidebarTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("descriptionAlertMessage", DescriptionAlertMessage);
            writer.WriteStringValue("descriptionPlaceholderText", DescriptionPlaceholderText);
            writer.WriteStringValue("footerMessage", FooterMessage);
            writer.WriteStringValue("headerAlertMessage", HeaderAlertMessage);
            writer.WriteGuidValue("providerId", ProviderId);
            writer.WriteStringValue("sessionSupportButtonTitle", SessionSupportButtonTitle);
            writer.WriteBoolValue("showSessionSupportConfirmCheckbox", ShowSessionSupportConfirmCheckbox);
            writer.WriteStringValue("supportSidebarTitle", SupportSidebarTitle);
        }
    }
}
#pragma warning restore CS0618
