// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetScriptVariablesAndParametersRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The computerId property</summary>
        public int? ComputerId { get; set; }
        /// <summary>The string or integer value may be used. SoftwareDetection = 0, SoftwareVersionAction = 2, MaintenanceTaskSetter = 3, MetascriptDeploymentTarget = 4, FilterScriptDeploymentTarget = 5, DeviceInventory = 6, Function = 7, ImmySystem = 8, DynamicVersions = 9, DownloadInstaller = 10, Module = 11, Preflight = 12, Integration = 13</summary>
        public global::Bezalu.ImmyBot.Client.Models.ScriptCategory? ScriptCategory { get; set; }
        /// <summary>The string or integer value may be used. System = 0, CurrentUser = 1, Metascript = 2, CloudScript = 4</summary>
        public global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext? ScriptExecutionContext { get; set; }
        /// <summary>The softwareId property</summary>
        public int? SoftwareId { get; set; }
        /// <summary>The string or integer value may be used. GlobalSoftware = 0, LocalSoftware = 1, WindowsUpdate = 2, Chocolatey = 3, Ninite = 4</summary>
        public global::Bezalu.ImmyBot.Client.Models.SoftwareType? SoftwareType { get; set; }
        /// <summary>The taskId property</summary>
        public int? TaskId { get; set; }
        /// <summary>The string or integer value may be used. Global = 0, Local = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.DatabaseType? TaskType { get; set; }
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetScriptVariablesAndParametersRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetScriptVariablesAndParametersRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetScriptVariablesAndParametersRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "computerId", n => { ComputerId = n.GetIntValue(); } },
                { "scriptCategory", n => { ScriptCategory = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptCategory>(); } },
                { "scriptExecutionContext", n => { ScriptExecutionContext = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext>(); } },
                { "softwareId", n => { SoftwareId = n.GetIntValue(); } },
                { "softwareType", n => { SoftwareType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SoftwareType>(); } },
                { "taskId", n => { TaskId = n.GetIntValue(); } },
                { "taskType", n => { TaskType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>(); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("computerId", ComputerId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptCategory>("scriptCategory", ScriptCategory);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptExecutionContext>("scriptExecutionContext", ScriptExecutionContext);
            writer.WriteIntValue("softwareId", SoftwareId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SoftwareType>("softwareType", SoftwareType);
            writer.WriteIntValue("taskId", TaskId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>("taskType", TaskType);
            writer.WriteIntValue("tenantId", TenantId);
        }
    }
}
#pragma warning restore CS0618
