// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetUserResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The azurePrincipalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AzurePrincipalId { get; set; }
#nullable restore
#else
        public string AzurePrincipalId { get; set; }
#endif
        /// <summary>The canManageCrossTenantDeployments property</summary>
        public bool? CanManageCrossTenantDeployments { get; set; }
        /// <summary>The companyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The directRoleCount property</summary>
        public int? DirectRoleCount { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The expirationDateUTC property</summary>
        public DateTimeOffset? ExpirationDateUTC { get; set; }
        /// <summary>The groupCount property</summary>
        public int? GroupCount { get; set; }
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Groups { get; set; }
#nullable restore
#else
        public List<string> Groups { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isAdmin property</summary>
        public bool? IsAdmin { get; set; }
        /// <summary>The isExpired property</summary>
        public bool? IsExpired { get; set; }
        /// <summary>The isMsp property</summary>
        public bool? IsMsp { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The personId property</summary>
        public int? PersonId { get; set; }
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetUserResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.GetUserResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.GetUserResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "azurePrincipalId", n => { AzurePrincipalId = n.GetStringValue(); } },
                { "canManageCrossTenantDeployments", n => { CanManageCrossTenantDeployments = n.GetBoolValue(); } },
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "directRoleCount", n => { DirectRoleCount = n.GetIntValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "expirationDateUTC", n => { ExpirationDateUTC = n.GetDateTimeOffsetValue(); } },
                { "groupCount", n => { GroupCount = n.GetIntValue(); } },
                { "groups", n => { Groups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isAdmin", n => { IsAdmin = n.GetBoolValue(); } },
                { "isExpired", n => { IsExpired = n.GetBoolValue(); } },
                { "isMsp", n => { IsMsp = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "personId", n => { PersonId = n.GetIntValue(); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("azurePrincipalId", AzurePrincipalId);
            writer.WriteBoolValue("canManageCrossTenantDeployments", CanManageCrossTenantDeployments);
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteIntValue("directRoleCount", DirectRoleCount);
            writer.WriteStringValue("email", Email);
            writer.WriteDateTimeOffsetValue("expirationDateUTC", ExpirationDateUTC);
            writer.WriteIntValue("groupCount", GroupCount);
            writer.WriteCollectionOfPrimitiveValues<string>("groups", Groups);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isAdmin", IsAdmin);
            writer.WriteBoolValue("isExpired", IsExpired);
            writer.WriteBoolValue("isMsp", IsMsp);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("personId", PersonId);
            writer.WriteIntValue("tenantId", TenantId);
            writer.WriteStringValue("type", Type);
        }
    }
}
#pragma warning restore CS0618
