// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. ComputerName = 0, SerialNumber = 1, Manufacturer = 2, Model = 3, OperatingSystem = 4, InternalIpAddress = 5, ExternalIpAddress = 6, Domain = 7, LastLoggedOnUser = 8, LastBootTimeUtc = 9, OSInstallDate = 10, ImmybotRemoteControlUrl = 11, CWScreenConnectRemoteControlUrl = 12, ImmyComputerId = 13, PrimaryPersonFullName = 14, PrimaryPersonEmail = 15</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImmyComputerField
    {
        [EnumMember(Value = "ComputerName")]
        #pragma warning disable CS1591
        ComputerName,
        #pragma warning restore CS1591
        [EnumMember(Value = "SerialNumber")]
        #pragma warning disable CS1591
        SerialNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "Manufacturer")]
        #pragma warning disable CS1591
        Manufacturer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Model")]
        #pragma warning disable CS1591
        Model,
        #pragma warning restore CS1591
        [EnumMember(Value = "OperatingSystem")]
        #pragma warning disable CS1591
        OperatingSystem,
        #pragma warning restore CS1591
        [EnumMember(Value = "InternalIpAddress")]
        #pragma warning disable CS1591
        InternalIpAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExternalIpAddress")]
        #pragma warning disable CS1591
        ExternalIpAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "Domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastLoggedOnUser")]
        #pragma warning disable CS1591
        LastLoggedOnUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastBootTimeUtc")]
        #pragma warning disable CS1591
        LastBootTimeUtc,
        #pragma warning restore CS1591
        [EnumMember(Value = "OSInstallDate")]
        #pragma warning disable CS1591
        OSInstallDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ImmybotRemoteControlUrl")]
        #pragma warning disable CS1591
        ImmybotRemoteControlUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "CWScreenConnectRemoteControlUrl")]
        #pragma warning disable CS1591
        CWScreenConnectRemoteControlUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "ImmyComputerId")]
        #pragma warning disable CS1591
        ImmyComputerId,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrimaryPersonFullName")]
        #pragma warning disable CS1591
        PrimaryPersonFullName,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrimaryPersonEmail")]
        #pragma warning disable CS1591
        PrimaryPersonEmail,
        #pragma warning restore CS1591
    }
}
