// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Developer = 1, Alpha = 2, Beta = 3, Production = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IntegrationTag
    {
        [EnumMember(Value = "Developer")]
        #pragma warning disable CS1591
        Developer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Alpha")]
        #pragma warning disable CS1591
        Alpha,
        #pragma warning restore CS1591
        [EnumMember(Value = "Beta")]
        #pragma warning disable CS1591
        Beta,
        #pragma warning restore CS1591
        [EnumMember(Value = "Production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
    }
}
