// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. SpecifiedNumMinutes = 0, EveryMinute = 1, Hourly = 2, Daily = 3, Weekly = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InventoryTaskFrequency
    {
        [EnumMember(Value = "SpecifiedNumMinutes")]
        #pragma warning disable CS1591
        SpecifiedNumMinutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "EveryMinute")]
        #pragma warning disable CS1591
        EveryMinute,
        #pragma warning restore CS1591
        [EnumMember(Value = "Hourly")]
        #pragma warning disable CS1591
        Hourly,
        #pragma warning restore CS1591
        [EnumMember(Value = "Daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "Weekly")]
        #pragma warning disable CS1591
        Weekly,
        #pragma warning restore CS1591
    }
}
