// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IProviderAgentDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The agentVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.SemanticVersion? AgentVersion { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.SemanticVersion AgentVersion { get; set; }
#endif
        /// <summary>The deviceDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.DeviceDetails? DeviceDetails { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.DeviceDetails DeviceDetails { get; set; }
#endif
        /// <summary>The externalAgentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.ExternalAgentId? ExternalAgentId { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.ExternalAgentId ExternalAgentId { get; set; }
#endif
        /// <summary>The externalClientId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalClientId { get; set; }
#nullable restore
#else
        public string ExternalClientId { get; set; }
#endif
        /// <summary>The internalData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? InternalData { get; private set; }
#nullable restore
#else
        public UntypedNode InternalData { get; private set; }
#endif
        /// <summary>The isOnline property</summary>
        public bool? IsOnline { get; private set; }
        /// <summary>The lastUpdatedUTC property</summary>
        public DateTimeOffset? LastUpdatedUTC { get; private set; }
        /// <summary>The onboardingOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions? OnboardingOptions { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions OnboardingOptions { get; set; }
#endif
        /// <summary>The requireManualIdentification property</summary>
        public bool? RequireManualIdentification { get; private set; }
        /// <summary>The supportsRunningScripts property</summary>
        public bool? SupportsRunningScripts { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.IProviderAgentDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.IProviderAgentDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.IProviderAgentDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agentVersion", n => { AgentVersion = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.SemanticVersion>(global::Bezalu.ImmyBot.Client.Models.SemanticVersion.CreateFromDiscriminatorValue); } },
                { "deviceDetails", n => { DeviceDetails = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.DeviceDetails>(global::Bezalu.ImmyBot.Client.Models.DeviceDetails.CreateFromDiscriminatorValue); } },
                { "externalAgentId", n => { ExternalAgentId = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.ExternalAgentId>(global::Bezalu.ImmyBot.Client.Models.ExternalAgentId.CreateFromDiscriminatorValue); } },
                { "externalClientId", n => { ExternalClientId = n.GetStringValue(); } },
                { "internalData", n => { InternalData = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "isOnline", n => { IsOnline = n.GetBoolValue(); } },
                { "lastUpdatedUTC", n => { LastUpdatedUTC = n.GetDateTimeOffsetValue(); } },
                { "onboardingOptions", n => { OnboardingOptions = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions>(global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions.CreateFromDiscriminatorValue); } },
                { "requireManualIdentification", n => { RequireManualIdentification = n.GetBoolValue(); } },
                { "supportsRunningScripts", n => { SupportsRunningScripts = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.SemanticVersion>("agentVersion", AgentVersion);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.DeviceDetails>("deviceDetails", DeviceDetails);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.ExternalAgentId>("externalAgentId", ExternalAgentId);
            writer.WriteStringValue("externalClientId", ExternalClientId);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.AgentOnboardingOptions>("onboardingOptions", OnboardingOptions);
        }
    }
}
#pragma warning restore CS0618
