// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Sequential = 0, Explicit = 2, Auto = 3</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LayoutKind
    {
        [EnumMember(Value = "Sequential")]
        #pragma warning disable CS1591
        Sequential,
        #pragma warning restore CS1591
        [EnumMember(Value = "Explicit")]
        #pragma warning disable CS1591
        Explicit,
        #pragma warning restore CS1591
        [EnumMember(Value = "Auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
