// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. None = 0, LicenseFile = 1, Key = 2</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LicenseType
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "LicenseFile")]
        #pragma warning disable CS1591
        LicenseFile,
        #pragma warning restore CS1591
        [EnumMember(Value = "Key")]
        #pragma warning disable CS1591
        Key,
        #pragma warning restore CS1591
    }
}
