// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Number = 0, Text = 1, Boolean = 2, Select = 3, Password = 4, File = 5, Uri = 6, KeyValuePair = 7</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MaintenanceTaskParameterType
    {
        [EnumMember(Value = "Number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "Text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "Boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "Select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
        [EnumMember(Value = "Password")]
        #pragma warning disable CS1591
        Password,
        #pragma warning restore CS1591
        [EnumMember(Value = "File")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
        [EnumMember(Value = "Uri")]
        #pragma warning disable CS1591
        Uri,
        #pragma warning restore CS1591
        [EnumMember(Value = "KeyValuePair")]
        #pragma warning disable CS1591
        KeyValuePair,
        #pragma warning restore CS1591
    }
}
