// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. SoftwareMissing = 0, UpdateAvailable = 1, UpToDate = 2, NotAssigned = 3, TestFailed = 4, SoftwareDetected = 5, OlderVersionRequired = 6, NoApplicableSoftwareVersion = 7, NoAction = 8, Undetermined = 9, TaskEnforce = 10, TaskAudit = 11, TaskMonitor = 12, TaskNotCompliant = 13, TaskCompliant = 14, DeviceOffline = 15, RepairTriggered = 16</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MaintenanceActionReason
    {
        [EnumMember(Value = "SoftwareMissing")]
        #pragma warning disable CS1591
        SoftwareMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "UpdateAvailable")]
        #pragma warning disable CS1591
        UpdateAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "UpToDate")]
        #pragma warning disable CS1591
        UpToDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotAssigned")]
        #pragma warning disable CS1591
        NotAssigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "TestFailed")]
        #pragma warning disable CS1591
        TestFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "SoftwareDetected")]
        #pragma warning disable CS1591
        SoftwareDetected,
        #pragma warning restore CS1591
        [EnumMember(Value = "OlderVersionRequired")]
        #pragma warning disable CS1591
        OlderVersionRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoApplicableSoftwareVersion")]
        #pragma warning disable CS1591
        NoApplicableSoftwareVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoAction")]
        #pragma warning disable CS1591
        NoAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "Undetermined")]
        #pragma warning disable CS1591
        Undetermined,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaskEnforce")]
        #pragma warning disable CS1591
        TaskEnforce,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaskAudit")]
        #pragma warning disable CS1591
        TaskAudit,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaskMonitor")]
        #pragma warning disable CS1591
        TaskMonitor,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaskNotCompliant")]
        #pragma warning disable CS1591
        TaskNotCompliant,
        #pragma warning restore CS1591
        [EnumMember(Value = "TaskCompliant")]
        #pragma warning disable CS1591
        TaskCompliant,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeviceOffline")]
        #pragma warning disable CS1591
        DeviceOffline,
        #pragma warning restore CS1591
        [EnumMember(Value = "RepairTriggered")]
        #pragma warning disable CS1591
        RepairTriggered,
        #pragma warning restore CS1591
    }
}
