// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MaintenanceEmailConfiguration : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The sendDetectionEmail property</summary>
        public bool? SendDetectionEmail { get; set; }
        /// <summary>The sendDetectionEmailWhenAllActionsAreCompliant property</summary>
        public bool? SendDetectionEmailWhenAllActionsAreCompliant { get; set; }
        /// <summary>The sendFollowUpEmail property</summary>
        public bool? SendFollowUpEmail { get; set; }
        /// <summary>The sendFollowUpOnlyIfActionNeeded property</summary>
        public bool? SendFollowUpOnlyIfActionNeeded { get; set; }
        /// <summary>The showMaintenanceActions property</summary>
        public bool? ShowMaintenanceActions { get; set; }
        /// <summary>The showPostponeButton property</summary>
        public bool? ShowPostponeButton { get; set; }
        /// <summary>The showRunNowButton property</summary>
        public bool? ShowRunNowButton { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.MaintenanceEmailConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.MaintenanceEmailConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.MaintenanceEmailConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "sendDetectionEmail", n => { SendDetectionEmail = n.GetBoolValue(); } },
                { "sendDetectionEmailWhenAllActionsAreCompliant", n => { SendDetectionEmailWhenAllActionsAreCompliant = n.GetBoolValue(); } },
                { "sendFollowUpEmail", n => { SendFollowUpEmail = n.GetBoolValue(); } },
                { "sendFollowUpOnlyIfActionNeeded", n => { SendFollowUpOnlyIfActionNeeded = n.GetBoolValue(); } },
                { "showMaintenanceActions", n => { ShowMaintenanceActions = n.GetBoolValue(); } },
                { "showPostponeButton", n => { ShowPostponeButton = n.GetBoolValue(); } },
                { "showRunNowButton", n => { ShowRunNowButton = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("sendDetectionEmail", SendDetectionEmail);
            writer.WriteBoolValue("sendDetectionEmailWhenAllActionsAreCompliant", SendDetectionEmailWhenAllActionsAreCompliant);
            writer.WriteBoolValue("sendFollowUpEmail", SendFollowUpEmail);
            writer.WriteBoolValue("sendFollowUpOnlyIfActionNeeded", SendFollowUpOnlyIfActionNeeded);
            writer.WriteBoolValue("showMaintenanceActions", ShowMaintenanceActions);
            writer.WriteBoolValue("showPostponeButton", ShowPostponeButton);
            writer.WriteBoolValue("showRunNowButton", ShowRunNowButton);
        }
    }
}
#pragma warning restore CS0618
