// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. ProviderHealth = 1, AccessRequested = 2, LargeScriptOutput = 3, UnacknowledgedDeployments = 4, UpdateInstance = 5, ProviderAgentsRequiringManualDecision = 6, AzureTenantProblems = 7, AzureCustomerPreconsentFailed = 8, AzureMultiCustomerPreconsentFailed = 9, ChangeRequestCreatedOrUpdated = 10, ChangeRequestAcknowledged = 11, ProviderRecommendation = 12, FeatureUsageExceeded = 13, TenantDeletion = 14, ScheduleFailed = 15</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NotificationType
    {
        [EnumMember(Value = "ProviderHealth")]
        #pragma warning disable CS1591
        ProviderHealth,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccessRequested")]
        #pragma warning disable CS1591
        AccessRequested,
        #pragma warning restore CS1591
        [EnumMember(Value = "LargeScriptOutput")]
        #pragma warning disable CS1591
        LargeScriptOutput,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnacknowledgedDeployments")]
        #pragma warning disable CS1591
        UnacknowledgedDeployments,
        #pragma warning restore CS1591
        [EnumMember(Value = "UpdateInstance")]
        #pragma warning disable CS1591
        UpdateInstance,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProviderAgentsRequiringManualDecision")]
        #pragma warning disable CS1591
        ProviderAgentsRequiringManualDecision,
        #pragma warning restore CS1591
        [EnumMember(Value = "AzureTenantProblems")]
        #pragma warning disable CS1591
        AzureTenantProblems,
        #pragma warning restore CS1591
        [EnumMember(Value = "AzureCustomerPreconsentFailed")]
        #pragma warning disable CS1591
        AzureCustomerPreconsentFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "AzureMultiCustomerPreconsentFailed")]
        #pragma warning disable CS1591
        AzureMultiCustomerPreconsentFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ChangeRequestCreatedOrUpdated")]
        #pragma warning disable CS1591
        ChangeRequestCreatedOrUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "ChangeRequestAcknowledged")]
        #pragma warning disable CS1591
        ChangeRequestAcknowledged,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProviderRecommendation")]
        #pragma warning disable CS1591
        ProviderRecommendation,
        #pragma warning restore CS1591
        [EnumMember(Value = "FeatureUsageExceeded")]
        #pragma warning disable CS1591
        FeatureUsageExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "TenantDeletion")]
        #pragma warning disable CS1591
        TenantDeletion,
        #pragma warning restore CS1591
        [EnumMember(Value = "ScheduleFailed")]
        #pragma warning disable CS1591
        ScheduleFailed,
        #pragma warning restore CS1591
    }
}
