// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Unacknowledged = 1, Acknowledged = 2, Dismissed = 3</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NotificationAcknowledgement
    {
        [EnumMember(Value = "Unacknowledged")]
        #pragma warning disable CS1591
        Unacknowledged,
        #pragma warning restore CS1591
        [EnumMember(Value = "Acknowledged")]
        #pragma warning disable CS1591
        Acknowledged,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dismissed")]
        #pragma warning disable CS1591
        Dismissed,
        #pragma warning restore CS1591
    }
}
