// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. OauthClientSecretRepository = 0, AzureTenantAuthDetails = 1</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OauthClientSecretSource
    {
        [EnumMember(Value = "OauthClientSecretRepository")]
        #pragma warning disable CS1591
        OauthClientSecretRepository,
        #pragma warning restore CS1591
        [EnumMember(Value = "AzureTenantAuthDetails")]
        #pragma warning disable CS1591
        AzureTenantAuthDetails,
        #pragma warning restore CS1591
    }
}
