// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Parameter : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowNull property</summary>
        public bool? AllowNull { get; set; }
        /// <summary>The apiDropdownKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiDropdownKey { get; set; }
#nullable restore
#else
        public string ApiDropdownKey { get; set; }
#endif
        /// <summary>The dateOnly property</summary>
        public bool? DateOnly { get; set; }
        /// <summary>The defaultValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DefaultValue { get; set; }
#nullable restore
#else
        public UntypedNode DefaultValue { get; set; }
#endif
        /// <summary>The defaultValueText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultValueText { get; set; }
#nullable restore
#else
        public string DefaultValueText { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The hasDropdownParameterSet property</summary>
        public bool? HasDropdownParameterSet { get; set; }
        /// <summary>The hasParameterSet property</summary>
        public bool? HasParameterSet { get; set; }
        /// <summary>The helpText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpText { get; set; }
#nullable restore
#else
        public string HelpText { get; set; }
#endif
        /// <summary>The hidden property</summary>
        public bool? Hidden { get; set; }
        /// <summary>The isMandatory property</summary>
        public bool? IsMandatory { get; set; }
        /// <summary>The isValueStripped property</summary>
        public bool? IsValueStripped { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The oauthConsentParameterData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.OauthConsentData? OauthConsentParameterData { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.OauthConsentData OauthConsentParameterData { get; set; }
#endif
        /// <summary>The onlyForHelpText property</summary>
        public bool? OnlyForHelpText { get; set; }
        /// <summary>The parameterType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.ParameterType? ParameterType { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.ParameterType ParameterType { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The showDropdownAsRadioButtons property</summary>
        public bool? ShowDropdownAsRadioButtons { get; set; }
        /// <summary>The showRawHelpText property</summary>
        public bool? ShowRawHelpText { get; set; }
        /// <summary>The useUtc property</summary>
        public bool? UseUtc { get; set; }
        /// <summary>The validDropdownValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.ParameterDropdownTextValue>? ValidDropdownValues { get; set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.ParameterDropdownTextValue> ValidDropdownValues { get; set; }
#endif
        /// <summary>The validParamSetValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ValidParamSetValues { get; set; }
#nullable restore
#else
        public List<string> ValidParamSetValues { get; set; }
#endif
        /// <summary>The valueFromPipeline property</summary>
        public bool? ValueFromPipeline { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.Parameter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.Parameter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.Parameter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowNull", n => { AllowNull = n.GetBoolValue(); } },
                { "apiDropdownKey", n => { ApiDropdownKey = n.GetStringValue(); } },
                { "dateOnly", n => { DateOnly = n.GetBoolValue(); } },
                { "defaultValue", n => { DefaultValue = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "defaultValueText", n => { DefaultValueText = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "hasDropdownParameterSet", n => { HasDropdownParameterSet = n.GetBoolValue(); } },
                { "hasParameterSet", n => { HasParameterSet = n.GetBoolValue(); } },
                { "helpText", n => { HelpText = n.GetStringValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "isMandatory", n => { IsMandatory = n.GetBoolValue(); } },
                { "isValueStripped", n => { IsValueStripped = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "oauthConsentParameterData", n => { OauthConsentParameterData = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.OauthConsentData>(global::Bezalu.ImmyBot.Client.Models.OauthConsentData.CreateFromDiscriminatorValue); } },
                { "onlyForHelpText", n => { OnlyForHelpText = n.GetBoolValue(); } },
                { "parameterType", n => { ParameterType = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.ParameterType>(global::Bezalu.ImmyBot.Client.Models.ParameterType.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "showDropdownAsRadioButtons", n => { ShowDropdownAsRadioButtons = n.GetBoolValue(); } },
                { "showRawHelpText", n => { ShowRawHelpText = n.GetBoolValue(); } },
                { "useUtc", n => { UseUtc = n.GetBoolValue(); } },
                { "validDropdownValues", n => { ValidDropdownValues = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.ParameterDropdownTextValue>(global::Bezalu.ImmyBot.Client.Models.ParameterDropdownTextValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "validParamSetValues", n => { ValidParamSetValues = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "valueFromPipeline", n => { ValueFromPipeline = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowNull", AllowNull);
            writer.WriteStringValue("apiDropdownKey", ApiDropdownKey);
            writer.WriteBoolValue("dateOnly", DateOnly);
            writer.WriteObjectValue<UntypedNode>("defaultValue", DefaultValue);
            writer.WriteStringValue("defaultValueText", DefaultValueText);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("hasDropdownParameterSet", HasDropdownParameterSet);
            writer.WriteBoolValue("hasParameterSet", HasParameterSet);
            writer.WriteStringValue("helpText", HelpText);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteBoolValue("isMandatory", IsMandatory);
            writer.WriteBoolValue("isValueStripped", IsValueStripped);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.OauthConsentData>("oauthConsentParameterData", OauthConsentParameterData);
            writer.WriteBoolValue("onlyForHelpText", OnlyForHelpText);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.ParameterType>("parameterType", ParameterType);
            writer.WriteIntValue("position", Position);
            writer.WriteBoolValue("showDropdownAsRadioButtons", ShowDropdownAsRadioButtons);
            writer.WriteBoolValue("showRawHelpText", ShowRawHelpText);
            writer.WriteBoolValue("useUtc", UseUtc);
            writer.WriteCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.ParameterDropdownTextValue>("validDropdownValues", ValidDropdownValues);
            writer.WriteCollectionOfPrimitiveValues<string>("validParamSetValues", ValidParamSetValues);
            writer.WriteBoolValue("valueFromPipeline", ValueFromPipeline);
        }
    }
}
#pragma warning restore CS0618
