// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PermissionAssignmentOverview : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowCount property</summary>
        public int? AllowCount { get; set; }
        /// <summary>The assignments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.ImmyBot.Client.Models.RoleAssignmentInfo>? Assignments { get; set; }
#nullable restore
#else
        public List<global::Bezalu.ImmyBot.Client.Models.RoleAssignmentInfo> Assignments { get; set; }
#endif
        /// <summary>The denyCount property</summary>
        public int? DenyCount { get; set; }
        /// <summary>The isResourceBased property</summary>
        public bool? IsResourceBased { get; set; }
        /// <summary>The permission property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Permission { get; set; }
#nullable restore
#else
        public string Permission { get; set; }
#endif
        /// <summary>The permissionDisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionDisplayName { get; set; }
#nullable restore
#else
        public string PermissionDisplayName { get; set; }
#endif
        /// <summary>The permissionName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionName { get; set; }
#nullable restore
#else
        public string PermissionName { get; set; }
#endif
        /// <summary>The subjectDisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectDisplayName { get; set; }
#nullable restore
#else
        public string SubjectDisplayName { get; set; }
#endif
        /// <summary>The subjectName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectName { get; set; }
#nullable restore
#else
        public string SubjectName { get; set; }
#endif
        /// <summary>The totalAssignments property</summary>
        public int? TotalAssignments { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.PermissionAssignmentOverview"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.PermissionAssignmentOverview CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.PermissionAssignmentOverview();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowCount", n => { AllowCount = n.GetIntValue(); } },
                { "assignments", n => { Assignments = n.GetCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.RoleAssignmentInfo>(global::Bezalu.ImmyBot.Client.Models.RoleAssignmentInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "denyCount", n => { DenyCount = n.GetIntValue(); } },
                { "isResourceBased", n => { IsResourceBased = n.GetBoolValue(); } },
                { "permission", n => { Permission = n.GetStringValue(); } },
                { "permissionDisplayName", n => { PermissionDisplayName = n.GetStringValue(); } },
                { "permissionName", n => { PermissionName = n.GetStringValue(); } },
                { "subjectDisplayName", n => { SubjectDisplayName = n.GetStringValue(); } },
                { "subjectName", n => { SubjectName = n.GetStringValue(); } },
                { "totalAssignments", n => { TotalAssignments = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("allowCount", AllowCount);
            writer.WriteCollectionOfObjectValues<global::Bezalu.ImmyBot.Client.Models.RoleAssignmentInfo>("assignments", Assignments);
            writer.WriteIntValue("denyCount", DenyCount);
            writer.WriteBoolValue("isResourceBased", IsResourceBased);
            writer.WriteStringValue("permission", Permission);
            writer.WriteStringValue("permissionDisplayName", PermissionDisplayName);
            writer.WriteStringValue("permissionName", PermissionName);
            writer.WriteStringValue("subjectDisplayName", SubjectDisplayName);
            writer.WriteStringValue("subjectName", SubjectName);
            writer.WriteIntValue("totalAssignments", TotalAssignments);
        }
    }
}
#pragma warning restore CS0618
