// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProvisioningPackageOptions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The disableHibernation property</summary>
        public bool? DisableHibernation { get; set; }
        /// <summary>The downloadISO property</summary>
        public bool? DownloadISO { get; set; }
        /// <summary>The enableCleanPC property</summary>
        public bool? EnableCleanPC { get; set; }
        /// <summary>The encryptPackage property</summary>
        public bool? EncryptPackage { get; set; }
        /// <summary>The hideAdminAccount property</summary>
        public bool? HideAdminAccount { get; set; }
        /// <summary>The localAdminPassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalAdminPassword { get; set; }
#nullable restore
#else
        public string LocalAdminPassword { get; set; }
#endif
        /// <summary>The localAdminUsername property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalAdminUsername { get; set; }
#nullable restore
#else
        public string LocalAdminUsername { get; set; }
#endif
        /// <summary>The packagePassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackagePassword { get; set; }
#nullable restore
#else
        public string PackagePassword { get; set; }
#endif
        /// <summary>The setupAdmin property</summary>
        public bool? SetupAdmin { get; set; }
        /// <summary>The setupWireless property</summary>
        public bool? SetupWireless { get; set; }
        /// <summary>The skipOobe property</summary>
        public bool? SkipOobe { get; set; }
        /// <summary>The wirelessKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WirelessKey { get; set; }
#nullable restore
#else
        public string WirelessKey { get; set; }
#endif
        /// <summary>The wirelessOpen property</summary>
        public bool? WirelessOpen { get; set; }
        /// <summary>The wirelessSSID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WirelessSSID { get; set; }
#nullable restore
#else
        public string WirelessSSID { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.ProvisioningPackageOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.ProvisioningPackageOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.ProvisioningPackageOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disableHibernation", n => { DisableHibernation = n.GetBoolValue(); } },
                { "downloadISO", n => { DownloadISO = n.GetBoolValue(); } },
                { "enableCleanPC", n => { EnableCleanPC = n.GetBoolValue(); } },
                { "encryptPackage", n => { EncryptPackage = n.GetBoolValue(); } },
                { "hideAdminAccount", n => { HideAdminAccount = n.GetBoolValue(); } },
                { "localAdminPassword", n => { LocalAdminPassword = n.GetStringValue(); } },
                { "localAdminUsername", n => { LocalAdminUsername = n.GetStringValue(); } },
                { "packagePassword", n => { PackagePassword = n.GetStringValue(); } },
                { "setupAdmin", n => { SetupAdmin = n.GetBoolValue(); } },
                { "setupWireless", n => { SetupWireless = n.GetBoolValue(); } },
                { "skipOobe", n => { SkipOobe = n.GetBoolValue(); } },
                { "wirelessKey", n => { WirelessKey = n.GetStringValue(); } },
                { "wirelessOpen", n => { WirelessOpen = n.GetBoolValue(); } },
                { "wirelessSSID", n => { WirelessSSID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("disableHibernation", DisableHibernation);
            writer.WriteBoolValue("downloadISO", DownloadISO);
            writer.WriteBoolValue("enableCleanPC", EnableCleanPC);
            writer.WriteBoolValue("encryptPackage", EncryptPackage);
            writer.WriteBoolValue("hideAdminAccount", HideAdminAccount);
            writer.WriteStringValue("localAdminPassword", LocalAdminPassword);
            writer.WriteStringValue("localAdminUsername", LocalAdminUsername);
            writer.WriteStringValue("packagePassword", PackagePassword);
            writer.WriteBoolValue("setupAdmin", SetupAdmin);
            writer.WriteBoolValue("setupWireless", SetupWireless);
            writer.WriteBoolValue("skipOobe", SkipOobe);
            writer.WriteStringValue("wirelessKey", WirelessKey);
            writer.WriteBoolValue("wirelessOpen", WirelessOpen);
            writer.WriteStringValue("wirelessSSID", WirelessSSID);
        }
    }
}
#pragma warning restore CS0618
