// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RunScriptRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The agentConnectionWaitTimeoutSeconds property</summary>
        public int? AgentConnectionWaitTimeoutSeconds { get; set; }
        /// <summary>The cancellationId property</summary>
        public Guid? CancellationId { get; set; }
        /// <summary>The computerId property</summary>
        public int? ComputerId { get; set; }
        /// <summary>The maintenanceActionId property</summary>
        public int? MaintenanceActionId { get; set; }
        /// <summary>The maintenanceSessionId property</summary>
        public int? MaintenanceSessionId { get; set; }
        /// <summary>The maintenanceTaskId property</summary>
        public int? MaintenanceTaskId { get; set; }
        /// <summary>The string or integer value may be used. Global = 0, Local = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.DatabaseType? MaintenanceTaskType { get; set; }
        /// <summary>The script property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBodyScript? Script { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBodyScript Script { get; set; }
#endif
        /// <summary>The sessionLogId property</summary>
        public int? SessionLogId { get; set; }
        /// <summary>The tenantId property</summary>
        public int? TenantId { get; set; }
        /// <summary>The terminalId property</summary>
        public Guid? TerminalId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agentConnectionWaitTimeoutSeconds", n => { AgentConnectionWaitTimeoutSeconds = n.GetIntValue(); } },
                { "cancellationId", n => { CancellationId = n.GetGuidValue(); } },
                { "computerId", n => { ComputerId = n.GetIntValue(); } },
                { "maintenanceActionId", n => { MaintenanceActionId = n.GetIntValue(); } },
                { "maintenanceSessionId", n => { MaintenanceSessionId = n.GetIntValue(); } },
                { "maintenanceTaskId", n => { MaintenanceTaskId = n.GetIntValue(); } },
                { "maintenanceTaskType", n => { MaintenanceTaskType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>(); } },
                { "script", n => { Script = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBodyScript>(global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBodyScript.CreateFromDiscriminatorValue); } },
                { "sessionLogId", n => { SessionLogId = n.GetIntValue(); } },
                { "tenantId", n => { TenantId = n.GetIntValue(); } },
                { "terminalId", n => { TerminalId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("agentConnectionWaitTimeoutSeconds", AgentConnectionWaitTimeoutSeconds);
            writer.WriteGuidValue("cancellationId", CancellationId);
            writer.WriteIntValue("computerId", ComputerId);
            writer.WriteIntValue("maintenanceActionId", MaintenanceActionId);
            writer.WriteIntValue("maintenanceSessionId", MaintenanceSessionId);
            writer.WriteIntValue("maintenanceTaskId", MaintenanceTaskId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>("maintenanceTaskType", MaintenanceTaskType);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.RunScriptRequestBodyScript>("script", Script);
            writer.WriteIntValue("sessionLogId", SessionLogId);
            writer.WriteIntValue("tenantId", TenantId);
            writer.WriteGuidValue("terminalId", TerminalId);
        }
    }
}
#pragma warning restore CS0618
