// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Object = 0, Table = 1</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScriptOutputType
    {
        [EnumMember(Value = "Object")]
        #pragma warning disable CS1591
        Object,
        #pragma warning restore CS1591
        [EnumMember(Value = "Table")]
        #pragma warning disable CS1591
        Table,
        #pragma warning restore CS1591
    }
}
