// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Software = 1, SoftwareVersion = 2, MaintenanceTask = 3</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScriptReferenceType
    {
        [EnumMember(Value = "Software")]
        #pragma warning disable CS1591
        Software,
        #pragma warning restore CS1591
        [EnumMember(Value = "SoftwareVersion")]
        #pragma warning disable CS1591
        SoftwareVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "MaintenanceTask")]
        #pragma warning disable CS1591
        MaintenanceTask,
        #pragma warning restore CS1591
    }
}
