// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. SoftwareDetection = 0, SoftwareVersionAction = 2, MaintenanceTaskSetter = 3, MetascriptDeploymentTarget = 4, FilterScriptDeploymentTarget = 5, DeviceInventory = 6, Function = 7, ImmySystem = 8, DynamicVersions = 9, DownloadInstaller = 10, Module = 11, Preflight = 12, Integration = 13</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScriptCategory
    {
        [EnumMember(Value = "SoftwareDetection")]
        #pragma warning disable CS1591
        SoftwareDetection,
        #pragma warning restore CS1591
        [EnumMember(Value = "SoftwareVersionAction")]
        #pragma warning disable CS1591
        SoftwareVersionAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "MaintenanceTaskSetter")]
        #pragma warning disable CS1591
        MaintenanceTaskSetter,
        #pragma warning restore CS1591
        [EnumMember(Value = "MetascriptDeploymentTarget")]
        #pragma warning disable CS1591
        MetascriptDeploymentTarget,
        #pragma warning restore CS1591
        [EnumMember(Value = "FilterScriptDeploymentTarget")]
        #pragma warning disable CS1591
        FilterScriptDeploymentTarget,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeviceInventory")]
        #pragma warning disable CS1591
        DeviceInventory,
        #pragma warning restore CS1591
        [EnumMember(Value = "Function")]
        #pragma warning disable CS1591
        Function,
        #pragma warning restore CS1591
        [EnumMember(Value = "ImmySystem")]
        #pragma warning disable CS1591
        ImmySystem,
        #pragma warning restore CS1591
        [EnumMember(Value = "DynamicVersions")]
        #pragma warning disable CS1591
        DynamicVersions,
        #pragma warning restore CS1591
        [EnumMember(Value = "DownloadInstaller")]
        #pragma warning disable CS1591
        DownloadInstaller,
        #pragma warning restore CS1591
        [EnumMember(Value = "Module")]
        #pragma warning disable CS1591
        Module,
        #pragma warning restore CS1591
        [EnumMember(Value = "Preflight")]
        #pragma warning disable CS1591
        Preflight,
        #pragma warning restore CS1591
        [EnumMember(Value = "Integration")]
        #pragma warning disable CS1591
        Integration,
        #pragma warning restore CS1591
    }
}
