// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScriptReference : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The string or integer value may be used. Global = 0, Local = 1</summary>
        public global::Bezalu.ImmyBot.Client.Models.DatabaseType? DatabaseType { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The string or integer value may be used. Software = 1, SoftwareVersion = 2, MaintenanceTask = 3</summary>
        public global::Bezalu.ImmyBot.Client.Models.ScriptReferenceType? ScriptReferenceType { get; set; }
        /// <summary>The softwareVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.ImmyBot.Client.Models.SemanticVersion? SoftwareVersion { get; set; }
#nullable restore
#else
        public global::Bezalu.ImmyBot.Client.Models.SemanticVersion SoftwareVersion { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.ScriptReference"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.ScriptReference CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.ScriptReference();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "databaseType", n => { DatabaseType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scriptReferenceType", n => { ScriptReferenceType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptReferenceType>(); } },
                { "softwareVersion", n => { SoftwareVersion = n.GetObjectValue<global::Bezalu.ImmyBot.Client.Models.SemanticVersion>(global::Bezalu.ImmyBot.Client.Models.SemanticVersion.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.DatabaseType>("databaseType", DatabaseType);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ScriptReferenceType>("scriptReferenceType", ScriptReferenceType);
            writer.WriteObjectValue<global::Bezalu.ImmyBot.Client.Models.SemanticVersion>("softwareVersion", SoftwareVersion);
        }
    }
}
#pragma warning restore CS0618
