// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionLogDisplayEvent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activityId property</summary>
        public int? ActivityId { get; set; }
        /// <summary>The contextMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextMessage { get; set; }
#nullable restore
#else
        public string ContextMessage { get; set; }
#endif
        /// <summary>The string or string value may be used. Output = 0, Debug = 1, Information = 2, Warning = 3, Verbose = 4, Progress = 5, Error = 6, Exception = 7</summary>
        public global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEventKind? EventKind { get; set; }
        /// <summary>The exceptionText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptionText { get; set; }
#nullable restore
#else
        public string ExceptionText { get; set; }
#endif
        /// <summary>The string or integer value may be used. Black = 0, DarkBlue = 1, DarkGreen = 2, DarkCyan = 3, DarkRed = 4, DarkMagenta = 5, DarkYellow = 6, Gray = 7, DarkGray = 8, Blue = 9, Green = 10, Cyan = 11, Red = 12, Magenta = 13, Yellow = 14, White = 15</summary>
        public global::Bezalu.ImmyBot.Client.Models.ConsoleColor? ForegroundColor { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The parentId property</summary>
        public int? ParentId { get; set; }
        /// <summary>The payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Payload { get; set; }
#nullable restore
#else
        public string Payload { get; set; }
#endif
        /// <summary>The progressActivity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgressActivity { get; set; }
#nullable restore
#else
        public string ProgressActivity { get; set; }
#endif
        /// <summary>The progressCompleted property</summary>
        public bool? ProgressCompleted { get; set; }
        /// <summary>The progressCorrelationId property</summary>
        public Guid? ProgressCorrelationId { get; set; }
        /// <summary>The progressCurrentOperation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgressCurrentOperation { get; set; }
#nullable restore
#else
        public string ProgressCurrentOperation { get; set; }
#endif
        /// <summary>The progressPercentComplete property</summary>
        public double? ProgressPercentComplete { get; set; }
        /// <summary>The progressSecondsRemaining property</summary>
        public double? ProgressSecondsRemaining { get; set; }
        /// <summary>The progressStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProgressStatus { get; set; }
#nullable restore
#else
        public string ProgressStatus { get; set; }
#endif
        /// <summary>The sequenceNumber property</summary>
        public long? SequenceNumber { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activityId", n => { ActivityId = n.GetIntValue(); } },
                { "contextMessage", n => { ContextMessage = n.GetStringValue(); } },
                { "eventKind", n => { EventKind = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEventKind>(); } },
                { "exceptionText", n => { ExceptionText = n.GetStringValue(); } },
                { "foregroundColor", n => { ForegroundColor = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.ConsoleColor>(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "parentId", n => { ParentId = n.GetIntValue(); } },
                { "payload", n => { Payload = n.GetStringValue(); } },
                { "progressActivity", n => { ProgressActivity = n.GetStringValue(); } },
                { "progressCompleted", n => { ProgressCompleted = n.GetBoolValue(); } },
                { "progressCorrelationId", n => { ProgressCorrelationId = n.GetGuidValue(); } },
                { "progressCurrentOperation", n => { ProgressCurrentOperation = n.GetStringValue(); } },
                { "progressPercentComplete", n => { ProgressPercentComplete = n.GetDoubleValue(); } },
                { "progressSecondsRemaining", n => { ProgressSecondsRemaining = n.GetDoubleValue(); } },
                { "progressStatus", n => { ProgressStatus = n.GetStringValue(); } },
                { "sequenceNumber", n => { SequenceNumber = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activityId", ActivityId);
            writer.WriteStringValue("contextMessage", ContextMessage);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.SessionLogDisplayEventKind>("eventKind", EventKind);
            writer.WriteStringValue("exceptionText", ExceptionText);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.ConsoleColor>("foregroundColor", ForegroundColor);
            writer.WriteStringValue("message", Message);
            writer.WriteIntValue("parentId", ParentId);
            writer.WriteStringValue("payload", Payload);
            writer.WriteStringValue("progressActivity", ProgressActivity);
            writer.WriteBoolValue("progressCompleted", ProgressCompleted);
            writer.WriteGuidValue("progressCorrelationId", ProgressCorrelationId);
            writer.WriteStringValue("progressCurrentOperation", ProgressCurrentOperation);
            writer.WriteDoubleValue("progressPercentComplete", ProgressPercentComplete);
            writer.WriteDoubleValue("progressSecondsRemaining", ProgressSecondsRemaining);
            writer.WriteStringValue("progressStatus", ProgressStatus);
            writer.WriteLongValue("sequenceNumber", SequenceNumber);
        }
    }
}
#pragma warning restore CS0618
