// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. Generic = 0, Error = 1, Command = 2, CommandResult = 3, Progress = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionLogType
    {
        [EnumMember(Value = "Generic")]
        #pragma warning disable CS1591
        Generic,
        #pragma warning restore CS1591
        [EnumMember(Value = "Error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "Command")]
        #pragma warning disable CS1591
        Command,
        #pragma warning restore CS1591
        [EnumMember(Value = "CommandResult")]
        #pragma warning disable CS1591
        CommandResult,
        #pragma warning restore CS1591
        [EnumMember(Value = "Progress")]
        #pragma warning disable CS1591
        Progress,
        #pragma warning restore CS1591
    }
}
