// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. GlobalSoftware = 0, LocalSoftware = 1, WindowsUpdate = 2, Chocolatey = 3, Ninite = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SoftwareType
    {
        [EnumMember(Value = "GlobalSoftware")]
        #pragma warning disable CS1591
        GlobalSoftware,
        #pragma warning restore CS1591
        [EnumMember(Value = "LocalSoftware")]
        #pragma warning disable CS1591
        LocalSoftware,
        #pragma warning restore CS1591
        [EnumMember(Value = "WindowsUpdate")]
        #pragma warning disable CS1591
        WindowsUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "Chocolatey")]
        #pragma warning disable CS1591
        Chocolatey,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ninite")]
        #pragma warning disable CS1591
        Ninite,
        #pragma warning restore CS1591
    }
}
