// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. AnyOf = 0, AllOf = 1</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubjectQualifier
    {
        [EnumMember(Value = "AnyOf")]
        #pragma warning disable CS1591
        AnyOf,
        #pragma warning restore CS1591
        [EnumMember(Value = "AllOf")]
        #pragma warning disable CS1591
        AllOf,
        #pragma warning restore CS1591
    }
}
