// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. UnKnown = 0, Day = 1, Week = 2, Month = 3, Year = 4</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionItemPriceUnit
    {
        [EnumMember(Value = "UnKnown")]
        #pragma warning disable CS1591
        UnKnown,
        #pragma warning restore CS1591
        [EnumMember(Value = "Day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "Week")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
        [EnumMember(Value = "Month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "Year")]
        #pragma warning disable CS1591
        Year,
        #pragma warning restore CS1591
    }
}
