// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. FlatFee = 0, PerUnit = 1, Tiered = 2, Volume = 3, Stairstep = 4, UnKnown = 5</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionItemPricingModel
    {
        [EnumMember(Value = "FlatFee")]
        #pragma warning disable CS1591
        FlatFee,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerUnit")]
        #pragma warning disable CS1591
        PerUnit,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tiered")]
        #pragma warning disable CS1591
        Tiered,
        #pragma warning restore CS1591
        [EnumMember(Value = "Volume")]
        #pragma warning disable CS1591
        Volume,
        #pragma warning restore CS1591
        [EnumMember(Value = "Stairstep")]
        #pragma warning disable CS1591
        Stairstep,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnKnown")]
        #pragma warning disable CS1591
        UnKnown,
        #pragma warning restore CS1591
    }
}
