// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    /// <summary>The string or integer value may be used. AgentConnected = 1, AgentDisconnected = 2, AgentCreated = 3, AgentDeleted = 4, MaintenanceActionStarted = 5, MaintenanceActionCompleted = 6, ComputerOnline = 7, ComputerOffline = 8, EphemeralAgentSessionCreated = 9, EphemeralAgentSessionConnected = 10, EphemeralAgentSessionConnectionTimeout = 11, EphemeralAgentSessionNotConnected = 12, EphemeralAgentSessionConnectionLost = 13, EphemeralAgentSessionIdleShutdown = 14, EphemeralAgentSessionZombieKill = 15, EphemeralAgentSessionCreationFailure = 16, EphemeralAgentSessionDisconnected = 17, RemoteSessionStarted = 18, RemoteSessionEnded = 19, EphemeralAgentSessionUpdateInstall = 20, AgentUpdated = 21, EphemeralAgentSessionAlreadyConnected = 22, EphemeralAgentSessionDisposed = 23</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimelineEventType
    {
        [EnumMember(Value = "AgentConnected")]
        #pragma warning disable CS1591
        AgentConnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "AgentDisconnected")]
        #pragma warning disable CS1591
        AgentDisconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "AgentCreated")]
        #pragma warning disable CS1591
        AgentCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "AgentDeleted")]
        #pragma warning disable CS1591
        AgentDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "MaintenanceActionStarted")]
        #pragma warning disable CS1591
        MaintenanceActionStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "MaintenanceActionCompleted")]
        #pragma warning disable CS1591
        MaintenanceActionCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "ComputerOnline")]
        #pragma warning disable CS1591
        ComputerOnline,
        #pragma warning restore CS1591
        [EnumMember(Value = "ComputerOffline")]
        #pragma warning disable CS1591
        ComputerOffline,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionCreated")]
        #pragma warning disable CS1591
        EphemeralAgentSessionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionConnected")]
        #pragma warning disable CS1591
        EphemeralAgentSessionConnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionConnectionTimeout")]
        #pragma warning disable CS1591
        EphemeralAgentSessionConnectionTimeout,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionNotConnected")]
        #pragma warning disable CS1591
        EphemeralAgentSessionNotConnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionConnectionLost")]
        #pragma warning disable CS1591
        EphemeralAgentSessionConnectionLost,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionIdleShutdown")]
        #pragma warning disable CS1591
        EphemeralAgentSessionIdleShutdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionZombieKill")]
        #pragma warning disable CS1591
        EphemeralAgentSessionZombieKill,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionCreationFailure")]
        #pragma warning disable CS1591
        EphemeralAgentSessionCreationFailure,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionDisconnected")]
        #pragma warning disable CS1591
        EphemeralAgentSessionDisconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "RemoteSessionStarted")]
        #pragma warning disable CS1591
        RemoteSessionStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "RemoteSessionEnded")]
        #pragma warning disable CS1591
        RemoteSessionEnded,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionUpdateInstall")]
        #pragma warning disable CS1591
        EphemeralAgentSessionUpdateInstall,
        #pragma warning restore CS1591
        [EnumMember(Value = "AgentUpdated")]
        #pragma warning disable CS1591
        AgentUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionAlreadyConnected")]
        #pragma warning disable CS1591
        EphemeralAgentSessionAlreadyConnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "EphemeralAgentSessionDisposed")]
        #pragma warning disable CS1591
        EphemeralAgentSessionDisposed,
        #pragma warning restore CS1591
    }
}
