// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.ImmyBot.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimelineEvent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Data { get; set; }
#nullable restore
#else
        public string Data { get; set; }
#endif
        /// <summary>The dateUTC property</summary>
        public DateTimeOffset? DateUTC { get; set; }
        /// <summary>The string or integer value may be used. AgentConnected = 1, AgentDisconnected = 2, AgentCreated = 3, AgentDeleted = 4, MaintenanceActionStarted = 5, MaintenanceActionCompleted = 6, ComputerOnline = 7, ComputerOffline = 8, EphemeralAgentSessionCreated = 9, EphemeralAgentSessionConnected = 10, EphemeralAgentSessionConnectionTimeout = 11, EphemeralAgentSessionNotConnected = 12, EphemeralAgentSessionConnectionLost = 13, EphemeralAgentSessionIdleShutdown = 14, EphemeralAgentSessionZombieKill = 15, EphemeralAgentSessionCreationFailure = 16, EphemeralAgentSessionDisconnected = 17, RemoteSessionStarted = 18, RemoteSessionEnded = 19, EphemeralAgentSessionUpdateInstall = 20, AgentUpdated = 21, EphemeralAgentSessionAlreadyConnected = 22, EphemeralAgentSessionDisposed = 23</summary>
        public global::Bezalu.ImmyBot.Client.Models.TimelineEventType? EventType { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identifier { get; private set; }
#nullable restore
#else
        public string Identifier { get; private set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The objectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The string or integer value may be used. Computer = 1, ProviderAgent = 2, Tenant = 3</summary>
        public global::Bezalu.ImmyBot.Client.Models.TimelineObjectType? ObjectType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.TimelineEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.ImmyBot.Client.Models.TimelineEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.ImmyBot.Client.Models.TimelineEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetStringValue(); } },
                { "dateUTC", n => { DateUTC = n.GetDateTimeOffsetValue(); } },
                { "eventType", n => { EventType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.TimelineEventType>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "identifier", n => { Identifier = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "objectId", n => { ObjectId = n.GetStringValue(); } },
                { "objectType", n => { ObjectType = n.GetEnumValue<global::Bezalu.ImmyBot.Client.Models.TimelineObjectType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("data", Data);
            writer.WriteDateTimeOffsetValue("dateUTC", DateUTC);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.TimelineEventType>("eventType", EventType);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("objectId", ObjectId);
            writer.WriteEnumValue<global::Bezalu.ImmyBot.Client.Models.TimelineObjectType>("objectType", ObjectType);
        }
    }
}
#pragma warning restore CS0618
