// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Dx;
using Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item;
using Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.OpenCount;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.ChangeRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\change-requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChangeRequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dx property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Dx.DxRequestBuilder Dx
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Dx.DxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The openCount property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.OpenCount.OpenCountRequestBuilder OpenCount
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.OpenCount.OpenCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.changeRequests.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.changeRequests.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.Item.ChangeRequestsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.ChangeRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeRequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/change-requests", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ChangeRequests.ChangeRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeRequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/change-requests", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
