// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\dynamic-provider-types\test-environment\{terminalId}\execute-method
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecuteMethodRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.dynamicProviderTypes.testEnvironment.item.executeMethod.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.Item.WithMethodItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.Item.WithMethodItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("method", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.Item.WithMethodItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.ExecuteMethodRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecuteMethodRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dynamic-provider-types/test-environment/{terminalId}/execute-method", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.DynamicProviderTypes.TestEnvironment.Item.ExecuteMethod.ExecuteMethodRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecuteMethodRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dynamic-provider-types/test-environment/{terminalId}/execute-method", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
