// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\azure-errors\for-tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForTenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.azureErrors.forTenant.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.Item.WithTenantPrincipalItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.Item.WithTenantPrincipalItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tenantPrincipalId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.Item.WithTenantPrincipalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.ForTenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForTenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/azure-errors/for-tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.AzureErrors.ForTenant.ForTenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForTenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/azure-errors/for-tenant", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
