// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Plugins.Api.V1.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Plugins.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \plugins\api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.plugins.api.v1.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providerLinkId", position);
                return new global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.plugins.api.v1.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("providerLinkId", position);
                return new global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
