// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\maintenance-actions\latest-non-compliant-actions-for-tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LatestNonCompliantActionsForTenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.maintenanceActions.latestNonCompliantActionsForTenant.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tenantId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.maintenanceActions.latestNonCompliantActionsForTenant.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("tenantId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.Item.WithTenantItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.LatestNonCompliantActionsForTenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestNonCompliantActionsForTenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-actions/latest-non-compliant-actions-for-tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.LatestNonCompliantActionsForTenant.LatestNonCompliantActionsForTenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestNonCompliantActionsForTenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-actions/latest-non-compliant-actions-for-tenant", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
