// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Plugins.Api.V1.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \plugins\api\v1\{providerLinkId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProviderLinkItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.plugins.api.v1.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.Item.WithCatchAllItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.Item.WithCatchAllItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("catchAll", position);
                return new global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.Item.WithCatchAllItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderLinkItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/api/v1/{providerLinkId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Plugins.Api.V1.Item.WithProviderLinkItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderLinkItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/plugins/api/v1/{providerLinkId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
