// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.DeleteOfflineAgentFromComputer;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.ExternalAgentUrl;
using Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.RefreshDeviceOnlineStatus;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\provider-links\{id}\agents\{agent-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deleteOfflineAgentFromComputer property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.DeleteOfflineAgentFromComputer.DeleteOfflineAgentFromComputerRequestBuilder DeleteOfflineAgentFromComputer
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.DeleteOfflineAgentFromComputer.DeleteOfflineAgentFromComputerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The externalAgentUrl property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.ExternalAgentUrl.ExternalAgentUrlRequestBuilder ExternalAgentUrl
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.ExternalAgentUrl.ExternalAgentUrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refreshDeviceOnlineStatus property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.RefreshDeviceOnlineStatus.RefreshDeviceOnlineStatusRequestBuilder RefreshDeviceOnlineStatus
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.RefreshDeviceOnlineStatus.RefreshDeviceOnlineStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/provider-links/{id}/agents/{agent%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.ProviderLinks.Item.Agents.Item.AgentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/provider-links/{id}/agents/{agent%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
