// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\notifications\{-id}\silence
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SilenceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SilenceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/notifications/{%2Did}/silence{?objectId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SilenceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/notifications/{%2Did}/silence{?objectId*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.UserSilencedNotificationResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.ImmyBot.Client.Models.UserSilencedNotificationResponse?> PostAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder.SilenceRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.ImmyBot.Client.Models.UserSilencedNotificationResponse> PostAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder.SilenceRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.ImmyBot.Client.Models.UserSilencedNotificationResponse>(requestInfo, global::Bezalu.ImmyBot.Client.Models.UserSilencedNotificationResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder.SilenceRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder.SilenceRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class SilenceRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("objectId")]
            public string? ObjectId { get; set; }
#nullable restore
#else
            [QueryParameter("objectId")]
            public string ObjectId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SilenceRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder.SilenceRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
