// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkCancel;
using Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkDelete;
using Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkRunNow;
using Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkUpdateStatus;
using Bezalu.ImmyBot.Client.Api.V1.Schedules.Item;
using Bezalu.ImmyBot.Client.Api.V1.Schedules.RunningScheduleIds;
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Schedules
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\schedules
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchedulesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulkCancel property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkCancel.BulkCancelRequestBuilder BulkCancel
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkCancel.BulkCancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulkDelete property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkDelete.BulkDeleteRequestBuilder BulkDelete
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkDelete.BulkDeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulkRunNow property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkRunNow.BulkRunNowRequestBuilder BulkRunNow
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkRunNow.BulkRunNowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulkUpdateStatus property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkUpdateStatus.BulkUpdateStatusRequestBuilder BulkUpdateStatus
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.BulkUpdateStatus.BulkUpdateStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runningScheduleIds property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.RunningScheduleIds.RunningScheduleIdsRequestBuilder RunningScheduleIds
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.RunningScheduleIds.RunningScheduleIdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.schedules.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("scheduleId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.schedules.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("scheduleId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.Item.WithScheduleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/schedules{?tenantId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/schedules{?tenantId*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse>?> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse>> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse>(requestInfo, global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse?> PostAsync(global::Bezalu.ImmyBot.Client.Models.CreateScheduleRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse> PostAsync(global::Bezalu.ImmyBot.Client.Models.CreateScheduleRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse>(requestInfo, global::Bezalu.ImmyBot.Client.Models.GetScheduleResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Bezalu.ImmyBot.Client.Models.CreateScheduleRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Bezalu.ImmyBot.Client.Models.CreateScheduleRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json-patch+json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class SchedulesRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("tenantId")]
            public int? TenantId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SchedulesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SchedulesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
