// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Computers.AddTags;
using Bezalu.ImmyBot.Client.Api.V1.Computers.AgentStatus;
using Bezalu.ImmyBot.Client.Api.V1.Computers.BulkDelete;
using Bezalu.ImmyBot.Client.Api.V1.Computers.ChangeTenant;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Dx;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Export;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Inventory;
using Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Item;
using Bezalu.ImmyBot.Client.Api.V1.Computers.My;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Onboarding;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Paged;
using Bezalu.ImmyBot.Client.Api.V1.Computers.RemoveTags;
using Bezalu.ImmyBot.Client.Api.V1.Computers.Restore;
using Bezalu.ImmyBot.Client.Api.V1.Computers.SetExcludedFromUserAffinity;
using Bezalu.ImmyBot.Client.Api.V1.Computers.SkipOnboarding;
using Bezalu.ImmyBot.Client.Api.V1.Computers.UserAffinities;
using Bezalu.ImmyBot.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Computers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\computers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComputersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addTags property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.AddTags.AddTagsRequestBuilder AddTags
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.AddTags.AddTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agentStatus property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.AgentStatus.AgentStatusRequestBuilder AgentStatus
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.AgentStatus.AgentStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulkDelete property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.BulkDelete.BulkDeleteRequestBuilder BulkDelete
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.BulkDelete.BulkDeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changeTenant property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.ChangeTenant.ChangeTenantRequestBuilder ChangeTenant
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.ChangeTenant.ChangeTenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dx property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Dx.DxRequestBuilder Dx
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Dx.DxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Export.ExportRequestBuilder Export
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inventory property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Inventory.InventoryRequestBuilder Inventory
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Inventory.InventoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inventorySoftware property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.InventorySoftwareRequestBuilder InventorySoftware
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.InventorySoftwareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The my property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.My.MyRequestBuilder My
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.My.MyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The onboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Onboarding.OnboardingRequestBuilder Onboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Onboarding.OnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paged property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Paged.PagedRequestBuilder Paged
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Paged.PagedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeTags property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.RemoveTags.RemoveTagsRequestBuilder RemoveTags
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.RemoveTags.RemoveTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Restore.RestoreRequestBuilder Restore
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setExcludedFromUserAffinity property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.SetExcludedFromUserAffinity.SetExcludedFromUserAffinityRequestBuilder SetExcludedFromUserAffinity
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.SetExcludedFromUserAffinity.SetExcludedFromUserAffinityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skipOnboarding property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.SkipOnboarding.SkipOnboardingRequestBuilder SkipOnboarding
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.SkipOnboarding.SkipOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userAffinities property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.UserAffinities.UserAffinitiesRequestBuilder UserAffinities
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.UserAffinities.UserAffinitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.computers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("computerId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.computers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("computerId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Computers.Item.WithComputerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComputersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/computers{?name*,orderByUpdatedDate*,pageSize*,tenantId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComputersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/computers{?name*,orderByUpdatedDate*,pageSize*,tenantId*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Bezalu.ImmyBot.Client.Models.ComputerSearch&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.ComputerSearch>?> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder.ComputersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Bezalu.ImmyBot.Client.Models.ComputerSearch>> GetAsync(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder.ComputersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Bezalu.ImmyBot.Client.Models.ComputerSearch>(requestInfo, global::Bezalu.ImmyBot.Client.Models.ComputerSearch.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder.ComputersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder.ComputersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ComputersRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            [QueryParameter("orderByUpdatedDate")]
            public bool? OrderByUpdatedDate { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            [QueryParameter("tenantId")]
            public int? TenantId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ComputersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.ImmyBot.Client.Api.V1.Computers.ComputersRequestBuilder.ComputersRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
