// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Oauth.BeginAuthCodeFlow;
using Bezalu.ImmyBot.Client.Api.V1.Oauth.FailAuthCodeFlow;
using Bezalu.ImmyBot.Client.Api.V1.Oauth.FinishAuthCodeFlow;
using Bezalu.ImmyBot.Client.Api.V1.Oauth.OauthAccessTokens;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Oauth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\oauth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OauthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The beginAuthCodeFlow property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Oauth.BeginAuthCodeFlow.BeginAuthCodeFlowRequestBuilder BeginAuthCodeFlow
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Oauth.BeginAuthCodeFlow.BeginAuthCodeFlowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The failAuthCodeFlow property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Oauth.FailAuthCodeFlow.FailAuthCodeFlowRequestBuilder FailAuthCodeFlow
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Oauth.FailAuthCodeFlow.FailAuthCodeFlowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The finishAuthCodeFlow property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Oauth.FinishAuthCodeFlow.FinishAuthCodeFlowRequestBuilder FinishAuthCodeFlow
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Oauth.FinishAuthCodeFlow.FinishAuthCodeFlowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauthAccessTokens property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Oauth.OauthAccessTokens.OauthAccessTokensRequestBuilder OauthAccessTokens
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Oauth.OauthAccessTokens.OauthAccessTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/oauth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/oauth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
