// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Billing.BillingInformation;
using Bezalu.ImmyBot.Client.Api.V1.Billing.BillingPlatformDetails;
using Bezalu.ImmyBot.Client.Api.V1.Billing.CancelSubscription;
using Bezalu.ImmyBot.Client.Api.V1.Billing.CreditCards;
using Bezalu.ImmyBot.Client.Api.V1.Billing.DownloadInvoice;
using Bezalu.ImmyBot.Client.Api.V1.Billing.FeatureUsageCounts;
using Bezalu.ImmyBot.Client.Api.V1.Billing.Information;
using Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalog;
using Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalogItems;
using Bezalu.ImmyBot.Client.Api.V1.Billing.ReactivateSubscription;
using Bezalu.ImmyBot.Client.Api.V1.Billing.SubscriptionDetails;
using Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateAddon;
using Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateSubscription;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Billing
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\billing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BillingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The billingInformation property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingInformation.BillingInformationRequestBuilder BillingInformation
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingInformation.BillingInformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The billingPlatformDetails property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingPlatformDetails.BillingPlatformDetailsRequestBuilder BillingPlatformDetails
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingPlatformDetails.BillingPlatformDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cancelSubscription property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.CancelSubscription.CancelSubscriptionRequestBuilder CancelSubscription
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.CancelSubscription.CancelSubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The creditCards property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.CreditCards.CreditCardsRequestBuilder CreditCards
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.CreditCards.CreditCardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadInvoice property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.DownloadInvoice.DownloadInvoiceRequestBuilder DownloadInvoice
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.DownloadInvoice.DownloadInvoiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The featureUsageCounts property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.FeatureUsageCounts.FeatureUsageCountsRequestBuilder FeatureUsageCounts
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.FeatureUsageCounts.FeatureUsageCountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The information property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.Information.InformationRequestBuilder Information
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.Information.InformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productCatalog property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalog.ProductCatalogRequestBuilder ProductCatalog
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalog.ProductCatalogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productCatalogItems property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalogItems.ProductCatalogItemsRequestBuilder ProductCatalogItems
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.ProductCatalogItems.ProductCatalogItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reactivateSubscription property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.ReactivateSubscription.ReactivateSubscriptionRequestBuilder ReactivateSubscription
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.ReactivateSubscription.ReactivateSubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptionDetails property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.SubscriptionDetails.SubscriptionDetailsRequestBuilder SubscriptionDetails
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.SubscriptionDetails.SubscriptionDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateAddon property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateAddon.UpdateAddonRequestBuilder UpdateAddon
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateAddon.UpdateAddonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateSubscription property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateSubscription.UpdateSubscriptionRequestBuilder UpdateSubscription
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Billing.UpdateSubscription.UpdateSubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BillingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/billing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BillingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/billing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
