// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Chocolatey.FindPackagesById;
using Bezalu.ImmyBot.Client.Api.V1.Chocolatey.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Chocolatey
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\chocolatey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChocolateyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The findPackagesById property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.FindPackagesById.FindPackagesByIdRequestBuilder FindPackagesById
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.FindPackagesById.FindPackagesByIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.Search.SearchRequestBuilder Search
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.ChocolateyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChocolateyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/chocolatey", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Chocolatey.ChocolateyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChocolateyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/chocolatey", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
