// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByName;
using Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByUpgradeCode;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\computers\inventory-software
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InventorySoftwareRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The searchByName property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByName.SearchByNameRequestBuilder SearchByName
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByName.SearchByNameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchByUpgradeCode property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByUpgradeCode.SearchByUpgradeCodeRequestBuilder SearchByUpgradeCode
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.SearchByUpgradeCode.SearchByUpgradeCodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.InventorySoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventorySoftwareRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/computers/inventory-software", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Computers.InventorySoftware.InventorySoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventorySoftwareRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/computers/inventory-software", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
