// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence;
using Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Unsilence;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Notifications.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\notifications\{-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The silence property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder Silence
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Silence.SilenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unsilence property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Unsilence.UnsilenceRequestBuilder Unsilence
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.Unsilence.UnsilenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/notifications/{%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Notifications.Item.ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/notifications/{%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
