// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item.Logs;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\maintenance-actions\{actionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithActionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The logs property</summary>
        public global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item.Logs.LogsRequestBuilder Logs
        {
            get => new global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item.WithActionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithActionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-actions/{actionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.MaintenanceActions.Item.WithActionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithActionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/maintenance-actions/{actionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
