// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\auth\get-azure-tenant-auth-details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAzureTenantAuthDetailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bezalu.ImmyBot.Client.api.v1.auth.getAzureTenantAuthDetails.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.Item.WithAzureTenantPrincipalItemRequestBuilder"/></returns>
        public global::Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.Item.WithAzureTenantPrincipalItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("azureTenantPrincipalId", position);
                return new global::Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.Item.WithAzureTenantPrincipalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.GetAzureTenantAuthDetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetAzureTenantAuthDetailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/auth/get-azure-tenant-auth-details", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.ImmyBot.Client.Api.V1.Auth.GetAzureTenantAuthDetails.GetAzureTenantAuthDetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetAzureTenantAuthDetailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/auth/get-azure-tenant-auth-details", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
